import assert from 'node:assert/strict';
const context={console,setTimeout,clearTimeout,Math,JSON,localStorage:{data:{},getItem(key){return this.data[key]??null;},setItem(key,value){this.data[key]=String(value);},removeItem(key){delete this.data[key];}},requestAnimationFrame(){},addEventListener(){},document:null};
class FakeGradient{addColorStop(){}}
class FakeContext{save(){}restore(){}translate(){}scale(){}rotate(){}beginPath(){}closePath(){}moveTo(){}lineTo(){}quadraticCurveTo(){}arc(){}ellipse(){}fill(){}stroke(){}fillRect(){}strokeRect(){}clearRect(){}roundRect(){}createLinearGradient(){return new FakeGradient();}createRadialGradient(){return new FakeGradient();}fillText(){}set globalAlpha(v){}}
function makeElement(){return{classList:{add(){},remove(){},contains(){return false;}},textContent:'',innerHTML:'',dataset:{},querySelector(){return makeElement();},querySelectorAll(){return[];},onclick:null,focus(){}};}
const canvas=makeElement();canvas.getContext=()=>new FakeContext();context.document={querySelector(selector){if(selector==='#game')return canvas;return makeElement();},querySelectorAll(){return[];}};Object.assign(globalThis,context);
await import(new URL('../game/main.js',import.meta.url).href+'?smoke='+Date.now());
const {state}=await import('../game/core/state.js');const {save,saveGame}=await import('../game/systems/save.js');const {buildMap}=await import('../game/world/maps.js');const {update}=await import('../game/core/update.js');const {startFishing,handleSpaceKey}=await import('../game/systems/fishing.js');const {capture}=await import('../game/systems/capture.js');const {ensureProgression,gatherNearest,craft,buyUpgrade,progressSummary}=await import('../game/systems/progression.js');
ensureProgression();for(let i=0;i<120;i++)update(1/60);assert.equal(state.map,'village');console.log('✔ vila: inicialização');
state.map='forest';buildMap();for(let i=0;i<180;i++)update(1/60);assert.equal(state.map,'forest');assert.ok(state.resources.length>0);console.log('✔ floresta: mundo + recursos=',state.resources.length);
const first=state.resources.find(r=>r.alive);state.player.x=first.x;state.player.y=first.y;const before=save.progression.stats.gathered;assert.equal(gatherNearest(),true);assert.ok(save.progression.stats.gathered>before);console.log('✔ coleta: recurso obtido');
save.progression.resources.wood=20;save.progression.resources.fiber=20;save.progression.resources.crystal=20;save.progression.resources.ore=20;save.progression.resources.mushroom=20;save.progression.level=10;assert.equal(craft('better_net'),true);assert.equal(save.inventory.reinforcedNet,1);assert.equal(craft('lantern'),true);assert.equal(save.inventory.lantern,1);console.log('✔ crafting: equipamentos permanentes');
save.coins=1000;assert.equal(buyUpgrade('pocket'),true);assert.equal(save.progression.upgrades.pocket,true);console.log('✔ upgrades: bolsa instalada');assert.ok(progressSummary().level>=1);
startFishing();for(let i=0;i<100;i++)update(1/60);assert.equal(state.fishing?.stage,'bite');handleSpaceKey();assert.equal(state.fishing?.stage,'reel');for(let i=0;i<180;i++)update(1/60);console.log('✔ pesca: ciclo resolvido');
state.map='cave';buildMap();for(let i=0;i<180;i++)update(1/60);assert.equal(state.map,'cave');capture();console.log('✔ caverna/captura: sem erro');save.map='cave';saveGame();assert.doesNotThrow(()=>JSON.parse(localStorage.getItem('firefly-save')));console.log('✔ save v3: JSON válido');console.log('\n✅ SMOKE TEST 3.0 PASSOU — progressão, coleta, crafting, upgrades, pesca e captura.');
