/* FireFly 7.4 — loop com polish */
'use strict';
import {canvas,ui} from './core/dom.js';import {keys,clearKeys,normalizeKey} from './core/input.js';import {state} from './core/state.js';import {saveGame} from './systems/save.js';import {AudioManager} from './systems/audio.js';import {panel} from './render/panel.js';import {update} from './core/update.js';import {render} from './render/world.js';import {renderFaunaOverlay} from './render/fauna-overlay.js';import {renderEventsOverlay} from './render/events-overlay.js';import {renderPolishOverlay} from './render/polish.js';import {buildMap,handleWorldInteraction,clickedInteractable} from './world/maps.js';import {handleSpaceKey} from './systems/fishing.js';import {ensureProgression} from './systems/progression.js';import {updateFireFly5} from './systems/firefly-5.js';
let lastTime=0,reportedError=false;function showRuntimeError(phase,error){if(reportedError)return;reportedError=true;console.error(`FireFly ${phase} error:`,error);const box=document.createElement('div');box.style.cssText='position:absolute;left:18px;right:18px;top:120px;z-index:20;padding:16px 18px;border:1px solid #d9b97a;background:#07171bf2;color:#f2dfb1;font:700 13px/1.5 system-ui;pointer-events:none;white-space:pre-wrap;';box.textContent=`FIREFLY PAROU NA INICIALIZAÇÃO (${phase})\n${error?.message||error}`;document.getElementById('gameShell')?.appendChild(box);}
function loop(now){const dt=Math.min(.033,(now-lastTime)/1000||0);lastTime=now;try{update(dt);updateFireFly5();}catch(e){showRuntimeError('UPDATE',e);return;}try{render();renderFaunaOverlay();renderEventsOverlay();renderPolishOverlay();}catch(e){showRuntimeError('RENDER',e);return;}requestAnimationFrame(loop);}
addEventListener('error',e=>showRuntimeError('GLOBAL',e.error||e.message));addEventListener('unhandledrejection',e=>showRuntimeError('PROMISE',e.reason));
addEventListener('keydown',event=>{AudioManager.unlock();const key=normalizeKey(event);if(['Space','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','KeyW','KeyA','KeyS','KeyD','ShiftLeft','ShiftRight'].includes(key))event.preventDefault();if(!event.repeat)keys.add(key);if(event.key===' ')handleSpaceKey();if(event.key==='e'||event.key==='E'){if(ui.dialog&&!ui.dialog.classList.contains('hidden'))return;handleWorldInteraction();}if(event.key==='i'||event.key==='I')panel('bag');if(event.key==='b'||event.key==='B')panel('book');if(event.key==='m'||event.key==='M')panel('quest');if(event.key==='p'||event.key==='P')panel('progress');if(event.key==='j'||event.key==='J')panel('map');if(event.key==='n'||event.key==='N'){state.clock=(state.clock+.125)%1;saveGame();}});addEventListener('keyup',event=>keys.delete(normalizeKey(event)));addEventListener('blur',clearKeys);addEventListener('visibilitychange',()=>{if(document.hidden)clearKeys();});
addEventListener('keydown',event=>{if(event.key==='Escape'){if(ui.dialog&&!ui.dialog.classList.contains('hidden')){ui.dialog.classList.add('hidden');return;}for(const selector of ['.panel','.modal','.overlay'])document.querySelectorAll(selector).forEach(el=>el.classList.add('hidden'));}});
document.querySelectorAll('[data-panel]').forEach(button=>button.onclick=()=>panel(button.dataset.panel));if(ui.mute)ui.mute.onclick=()=>{AudioManager.unlock();AudioManager.toggle();};canvas.addEventListener('pointerdown',event=>{canvas.focus();AudioManager.unlock();const r=canvas.getBoundingClientRect(),sx=(event.clientX-r.left)*(canvas.width/r.width),sy=(event.clientY-r.top)*(canvas.height/r.height);if(clickedInteractable(sx,sy))return;});canvas.addEventListener('contextmenu',event=>event.preventDefault());try{ensureProgression();buildMap();saveGame();AudioManager.playMusic(state.map);AudioManager.playAmbient(state.map);}catch(e){showRuntimeError('BOOT',e);}canvas.focus();requestAnimationFrame(loop);
