/* FireFly Gameplay 2.0 — canvas world, persistent gameplay systems, no DOM world objects. */
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),W=1280,H=720,keys=new Set();
const $=s=>document.querySelector(s),ui={coins:$('#coins'),time:$('#time'),prompt:$('#prompt'),panel:$('#panel'),dialog:$('#dialog'),toast:$('#toast')};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),rnd=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const DATA={version:2,coins:25,map:'village',inventory:{bait:0,reinforcedNet:0,lantern:0,explorationKit:0},catches:{},discovered:{},quests:{tito_frogs:{status:'available',progress:0}},audioEnabled:true};
function loadGame(){try{return {...DATA,...JSON.parse(localStorage.getItem('firefly-save')||'{}'),inventory:{...DATA.inventory,...JSON.parse(localStorage.getItem('firefly-save')||'{}').inventory},catches:{...DATA.catches,...JSON.parse(localStorage.getItem('firefly-save')||'{}').catches},discovered:{...DATA.discovered,...JSON.parse(localStorage.getItem('firefly-save')||'{}').discovered},quests:{...DATA.quests,...JSON.parse(localStorage.getItem('firefly-save')||'{}').quests}}}catch{return structuredClone(DATA)}}
const save=loadGame(); function saveGame(){localStorage.setItem('firefly-save',JSON.stringify(save));ui.coins.textContent=save.coins}
const AudioManager={musicVolume:.35,sfxVolume:.2,ambientVolume:.25,ctx:null,unlocked:false,assets:{},unlock(){if(this.unlocked||!save.audioEnabled)return;this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.unlocked=true},tone(f=440,d=.09,type='sine'){if(!this.unlocked||!save.audioEnabled)return;let o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(.0001,this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(this.sfxVolume,this.ctx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,this.ctx.currentTime+d);o.connect(g).connect(this.ctx.destination);o.start();o.stop(this.ctx.currentTime+d+.02)},playSFX(id){({capture:()=>{this.tone(660,.08);setTimeout(()=>this.tone(880,.12),70)},coin:()=>this.tone(980,.1),purchase:()=>{this.tone(520,.08);setTimeout(()=>this.tone(780,.12),90)},'quest-complete':()=>{this.tone(523,.1);setTimeout(()=>this.tone(784,.1),100);setTimeout(()=>this.tone(1046,.16),200)},'van-door':()=>this.tone(180,.12,'square'),'van-engine':()=>this.tone(90,.5,'sawtooth'),fish:()=>this.tone(340,.12)})[id]?.()},playMusic(){/* Optional local tracks are loaded only when supplied in assets/audio/music. */},playAmbient(){},toggle(){save.audioEnabled=!save.audioEnabled;saveGame();notify(save.audioEnabled?'Som ativado':'Som desativado')}};
const QUESTS={tito_frogs:{id:'tito_frogs',giver:'tito',title:'Um coro para a lagoa',target:'frog',required:3,reward:{coins:50,items:{bait:1}}}};
const SHOP=[['bait','Isca simples','Deixa peixes menos desconfiados.',10],['reinforcedNet','Rede reforçada','Necessária para capturas raras.',75],['lantern','Lanterna','Amplia a luz nas cavernas.',100],['explorationKit','Kit de exploração','Equipamento para rotas futuras.',150]];
const names={butterfly:'Borboleta-aurora',frog:'Sapo-musgo',lizard:'Lagartixa-folha',spider:'Aranha-das-rochas',firefly:'Vagalume-dourado',rare:'Vagalume-lilás',bat:'Morcego-de-veludo',mouse:'Rato-pedra',cavefly:'Vagalume-de-cristal',moonfish:'Peixe-lua',stripefish:'Peixe-listrado'};
const rarity={butterfly:'comum',frog:'comum',lizard:'incomum',spider:'incomum',firefly:'comum',rare:'raro',bat:'incomum',mouse:'comum',cavefly:'raro',moonfish:'comum',stripefish:'incomum'};
const state={map:save.map,clock:.54,t:0,player:{x:save.map==='village'?300:260,y:515,vx:0,face:1,action:0,mode:'idle'},camera:{x:0,target:0,shake:0},entities:[],particles:[],interactables:[],fade:{value:0,job:null},travel:0,fishing:null};
function notify(s){ui.toast.textContent=s;ui.toast.classList.add('show');clearTimeout(notify.id);notify.id=setTimeout(()=>ui.toast.classList.remove('show'),2300)}
function addParticles(x,y,color,count=12){for(let i=0;i<count;i++)state.particles.push({x,y,vx:rnd(-2.4,2.4),vy:rnd(-3.4,-.2),life:rnd(.45,1),color,size:rnd(2,5)})}
function transition(job){if(state.fade.job)return;state.fade.job=job;state.fade.value=.01}
function beginMap(id,x){transition(()=>{state.map=id;save.map=id;state.player.x=x;state.player.y=515;state.camera.x=0;state.entities=[];buildMap();saveGame();AudioManager.playMusic(id);AudioManager.playAmbient(id)})}
function addInteractable(id,x,y,radius,type,onInteract,label){state.interactables.push({id,x,y,radius,type,onInteract,label})}
function activeInteractable(){let p=state.player;return state.interactables.filter(o=>Math.abs(o.x-p.x)<o.radius&&Math.abs(o.y-p.y)<90).sort((a,b)=>Math.abs(a.x-p.x)-Math.abs(b.x-p.x))[0]}
function buildMap(){state.interactables=[]; if(state.map==='village'){addInteractable('tito',460,505,85,'npc',titoDialog,'Falar com Tito');addInteractable('shop',630,505,125,'shop',shopDialog,'Entrar na lojinha');addInteractable('van',1000,510,145,'vehicle',startVan,'Subir na van')} if(state.map==='forest'){spawnForest();addInteractable('fish',760,520,190,'fishing',startFishing,'Pescar no lago');addInteractable('cave',1590,510,135,'door',caveDialog,'Entrar na caverna');addInteractable('village',100,510,95,'door',()=>beginMap('village',1090),'Voltar para Vila Lumina')}if(state.map==='cave'){spawnCave();addInteractable('exit',120,510,100,'door',()=>beginMap('forest',1500),'Sair da caverna')}}
function spawn(type,x,y,opt={}){state.entities.push({type,x,y,homeX:x,homeY:y,vx:0,phase:rnd(0,6),mode:'wander',alive:true,rarity:rarity[type],...opt})}
function spawnForest(){[['butterfly',490,365],['butterfly',1250,330],['frog',690,512],['frog',835,500],['frog',1090,510],['lizard',1160,430],['spider',1560,490],['firefly',930,355],['rare',1370,340]].forEach(a=>spawn(...a))}
function spawnCave(){[['bat',570,270],['bat',1050,310],['spider',690,510],['mouse',900,515],['cavefly',1120,390],['rare',1380,350]].forEach(a=>spawn(...a))}
function quest(){return save.quests.tito_frogs} function acceptQuest(){quest().status='active';quest().progress=0;saveGame();closeDialog();notify('Missão aceita: capture 3 sapos.');AudioManager.playSFX('coin')}
function claimQuest(){let q=quest(),def=QUESTS.tito_frogs;if(q.status!=='complete')return;q.status='claimed';save.coins+=def.reward.coins;for(const[k,v]of Object.entries(def.reward.items))save.inventory[k]+=v;saveGame();closeDialog();addParticles(state.player.x,state.player.y,'#ffd66e',28);notify('MISSÃO CONCLUÍDA! +50 moedas, +1 Isca');AudioManager.playSFX('quest-complete')}
function titoDialog(){let q=quest();if(q.status==='available')dialog('Tito, inventor de redes','Ei! Você viu quantos sapos apareceram perto da floresta? Me traz 3 sapos e eu te dou umas moedas.',[['ACEITAR',acceptQuest],['AINDA NÃO',closeDialog]]);else if(q.status==='active')dialog('Tito','Estou ouvindo a lagoa daqui. Sapos encontrados: '+q.progress+' / 3.',[['VOLTAR',closeDialog]]);else if(q.status==='complete')dialog('Tito','Você conseguiu! Caramba, esses sapos são rápidos. Vamos acertar sua recompensa.',[['ENTREGAR SAPOS',claimQuest]]);else dialog('Tito','A rede parece feliz com você por perto. Obrigado pela ajuda com a lagoa!',[['TCHAU',closeDialog]])}
function shopDialog(){let rows=SHOP.map(([id,n,d,p])=>`<div class="card"><div><b>${n}</b><small>${d}</small><small>${p} moedas · possui ${save.inventory[id]}</small></div><button class="buy" data-buy="${id}">COMPRAR</button></div>`).join('');ui.dialog.innerHTML=`<button class="close">×</button><h2>Lojinha da Lumina</h2><p>Ferramentas honestas. Preços mais ou menos.</p>${rows}`;ui.dialog.classList.remove('hidden');ui.dialog.querySelector('.close').onclick=closeDialog;ui.dialog.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>buy(b.dataset.buy))}
function buy(id){let item=SHOP.find(x=>x[0]===id);if(save.coins<item[3]){notify('Você não tem moedas suficientes.');return}save.coins-=item[3];save.inventory[id]++;saveGame();addParticles(state.player.x,state.player.y,'#ffd66e',10);AudioManager.playSFX('purchase');notify('COMPRADO! +1 '+item[1]);shopDialog()}
function startVan(){if(state.travel)return;state.travel=1.5;AudioManager.playSFX('van-door');notify('A van sacode, a porta fecha...')}
function caveDialog(){dialog('Fenda Cintilante','Uma corrente fria e um brilho azul escapam lá de dentro.',[['ENTRAR NA CAVERNA',()=>{closeDialog();beginMap('cave',240)}],['AGORA NÃO',closeDialog]])}
function startFishing(){if(state.fishing)return;state.fishing={time:1.2,ready:false};state.player.action=1;notify('Você lança a linha. Espere a boia mexer...');AudioManager.playSFX('fish')}
function finishFishing(){let fish=Math.random()<.26?'stripefish':'moonfish';save.catches[fish]=(save.catches[fish]||0)+1;save.discovered[fish]=true;save.coins+=rarity[fish]==='incomum'?6:3;state.fishing=null;state.player.action=.7;addParticles(760,500,'#9ce4e2',16);saveGame();notify('Fisgou '+names[fish]+'!');AudioManager.playSFX('capture')}
function capture(){if(state.map==='village'||state.fishing?.ready){if(state.fishing?.ready)finishFishing();return}let p=state.player,e=state.entities.filter(e=>e.alive).sort((a,b)=>Math.abs(a.x-p.x)-Math.abs(b.x-p.x))[0];p.action=.6;if(!e||Math.abs(e.x-p.x)>105){notify('Escapou! A rede só pegou folhas.');addParticles(p.x+35*p.face,p.y,'#a5cf7d',5);return}if(e.rarity==='raro'&&!save.inventory.reinforcedNet){e.mode='flee';e.vx=260;notify('É raro demais para a sua rede atual!');return}e.alive=false;save.catches[e.type]=(save.catches[e.type]||0)+1;let fresh=!save.discovered[e.type];save.discovered[e.type]=true;save.coins+=e.rarity==='raro'?12:e.rarity==='incomum'?5:3;if(e.type==='frog'&&quest().status==='active'){quest().progress++;if(quest().progress>=QUESTS.tito_frogs.required){quest().status='complete';addParticles(e.x,e.y,'#ffe875',30);notify('MISSÃO COMPLETA! Volte para Tito.');AudioManager.playSFX('quest-complete')}else notify('Sapo capturado! '+quest().progress+'/3 para Tito.')}else notify((fresh?'NOVA DESCOBERTA! ':'')+names[e.type]+' capturado!');addParticles(e.x,e.y,e.rarity==='raro'?'#d2a1ff':'#ffe47a',16);state.camera.shake=8;saveGame();AudioManager.playSFX('capture')}
function dialog(title,body,actions){ui.dialog.innerHTML=`<button class="close">×</button><h2>${title}</h2><p>${body}</p>${actions.map((a,i)=>`<button class="choice action-${i}">${a[0]}</button>`).join('')}`;ui.dialog.classList.remove('hidden');ui.dialog.querySelector('.close').onclick=closeDialog;actions.forEach((a,i)=>ui.dialog.querySelector('.action-'+i).onclick=a[1])}function closeDialog(){ui.dialog.classList.add('hidden')}
function wx(x){return x-state.camera.x} function poly(p,fill,stroke){ctx.beginPath();p.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=3;ctx.stroke()}}
function txt(s,x,y,z=15,c='#fff',align='left'){ctx.fillStyle=c;ctx.font=`700 ${z}px system-ui`;ctx.textAlign=align;ctx.fillText(s,x,y)}
function sky(){let n=1-Math.abs(state.clock-.5)*2,g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,`rgb(${18+80*n},${35+170*n},${60+155*n})`);g.addColorStop(1,`rgb(${36+130*n},${63+150*n},${80+100*n})`);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);if(n<.4){ctx.fillStyle='#f3edca';ctx.beginPath();ctx.arc(1030,105,28,0,7);ctx.fill();for(let i=0;i<40;i++){ctx.fillStyle='#dbe9ce';ctx.fillRect((i*97)%W,(i*59)%300,2,2)}}else{ctx.fillStyle='#ffe9a2';ctx.beginPath();ctx.arc(1030,105,35,0,7);ctx.fill()}for(let l=0;l<3;l++){let ox=(state.camera.x*(.18+l*.16))%150;ctx.fillStyle=['#5aa27e','#377b69','#245c58'][l];for(let x=-160-ox;x<W+180;x+=118){ctx.beginPath();ctx.moveTo(x,450);ctx.quadraticCurveTo(x+35,285-l*25,x+70,430);ctx.quadraticCurveTo(x+99,315,x+130,450);ctx.fill()}}}
function ground(){ctx.fillStyle=state.map==='cave'?'#263d48':'#356b4d';ctx.fillRect(0,430,W,290);ctx.fillStyle=state.map==='cave'?'#415865':'#4d915b';ctx.fillRect(0,457,W,263);for(let x=-40;x<W+40;x+=27){ctx.strokeStyle=state.map==='cave'?'#5b7780':'#79b76b';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,460);ctx.lineTo(x+5,452+Math.sin(state.t+x)*3);ctx.stroke()}}
function tree(x,y,s,k=0){x=wx(x);ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.rotate(Math.sin(state.t*1.2+x)*.012);poly([[-15,168],[-38,188],[-12,180],[0,199],[14,179],[39,188],[20,164],[17,65],[-12,53]],'#654638','#363e42');ctx.fillStyle='#a36c4d';ctx.fillRect(-2,70,5,78);[['#4f9c5b',-28,30,44],['#397f51',19,24,51],['#62ae66',0,-8,55],['#4b9858',-38,-1,37],['#5dad65',37,-2,36]].forEach(([c,a,b,r])=>{ctx.fillStyle=c;ctx.beginPath();ctx.moveTo(a-r*.6,b+r*.3);ctx.quadraticCurveTo(a-r,b-r*.3,a,b-r);ctx.quadraticCurveTo(a+r,b-r*.25,a+r*.6,b+r*.4);ctx.quadraticCurveTo(a,b+r,a-r*.6,b+r*.3);ctx.fill()});ctx.restore()}
function flower(x,y,c){x=wx(x);ctx.strokeStyle='#326b44';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+2,y-19+Math.sin(state.t+x)*2);ctx.stroke();ctx.fillStyle=c;for(let i=0;i<5;i++){ctx.beginPath();ctx.ellipse(x+2+Math.cos(i*1.26)*5,y-23+Math.sin(i*1.26)*5,4,3,i,0,7);ctx.fill()}ctx.fillStyle='#ffe276';ctx.beginPath();ctx.arc(x+2,y-23,3,0,7);ctx.fill()}
function lake(){let x=wx(760),y=510;poly([[x-225,y+30],[x-192,y-16],[x-140,y-36],[x-89,y-30],[x-45,y-59],[x+35,y-49],[x+70,y-22],[x+155,y-27],[x+208,y+8],[x+182,y+45],[x+92,y+61],[x+19,y+48],[x-66,y+66],[x-147,y+49]],'#87684c','#3f674d');poly([[x-185,y+22],[x-151,y-4],[x-93,y-15],[x-40,y-40],[x+25,y-32],[x+73,y-8],[x+144,y-10],[x+173,y+11],[x+148,y+29],[x+89,y+39],[x+21,y+29],[x-53,y+47],[x-125,y+34]],'#3e98a9','#286b79');for(let i=0;i<8;i++){ctx.strokeStyle='#a5e4d9';ctx.beginPath();ctx.arc(x-135+i*40+Math.sin(state.t+i)*7,y+8+(i%3)*9,10,.1,2.7);ctx.stroke()}if(state.fishing){let bob=state.fishing.ready?Math.sin(state.t*18)*9:Math.sin(state.t*4)*2;ctx.strokeStyle='#e9d5ae';ctx.beginPath();ctx.moveTo(wx(state.player.x)+30,state.player.y-10);ctx.lineTo(x,y-10+bob);ctx.stroke();ctx.fillStyle='#f2c764';ctx.beginPath();ctx.arc(x,y-10+bob,5,0,7);ctx.fill()}}
function caveEntrance(){let x=wx(1590),y=460;poly([[x-130,105],[x-120,54],[x-92,18],[x-54,4],[x-20,-3],[x+13,17],[x+47,3],[x+86,24],[x+115,62],[x+123,105]],'#5c625c','#35464a');poly([[x-78,105],[x-69,58],[x-42,27],[x-4,19],[x+37,43],[x+65,72],[x+72,105]],'#162b38');for(let i=0;i<4;i++){ctx.fillStyle='#91ddb9';poly([[x-30+i*16,94],[x-24+i*16,68],[x-17+i*16,94]],'#91ddb9')}}
function caveWorld(){for(let x=0;x<W;x+=70){ctx.fillStyle='#2e4957';poly([[x,0],[x+35,40+(x%4)*14],[x+70,0]],'#2e4957');poly([[x,720],[x+32,650-(x%5)*10],[x+70,720]],'#314d59')}for(let i=0;i<12;i++){let x=(i*139)%W,y=330+(i%3)*85;ctx.fillStyle=i%2?'#6ccfca':'#a493e5';poly([[x,y],[x+8,y-26],[x+16,y]],ctx.fillStyle)}}
function house(){let x=wx(630),y=400;poly([[x-123,y+100],[x-113,y+36],[x-74,y-2],[x-8,y+15],[x+42,y-6],[x+109,y+36],[x+123,y+100]],'#d78e5a','#623f3c');poly([[x-133,y+40],[x-81,y-31],[x-3,y+2],[x+45,y-31],[x+129,y+41],[x+109,y+48],[x+39,y+8],[x-5,y+28],[x-84,y-20],[x-118,y+49]],'#9b5147','#623f3c');ctx.fillStyle='#f1c378';ctx.fillRect(x-50,y+58,35,42);ctx.fillStyle='#7bc0c4';ctx.fillRect(x+29,y+41,34,26);ctx.strokeStyle='#653f3e';ctx.strokeRect(x+29,y+41,34,26);txt('LOJINHA DA LUMINA',x,y+20,11,'#fff5c9','center')}
function van(){let x=wx(1000),y=520,shake=state.travel?Math.sin(state.t*38)*4:Math.sin(state.t*8);ctx.save();ctx.translate(x,y+shake);ctx.fillStyle='#203d4c88';ctx.beginPath();ctx.ellipse(-5,14,120,15,0,0,7);ctx.fill();ctx.fillStyle='#28495a';ctx.beginPath();ctx.roundRect(-112,-59,215,65,18);ctx.fill();ctx.fillStyle='#e37d4e';ctx.beginPath();ctx.roundRect(-106,-55,203,55,13);ctx.fill();poly([[-83,-59],[-55,-94],[28,-94],[59,-58]],'#e37d4e','#28495a');ctx.fillStyle='#9bd5da';ctx.fillRect(-49,-86,35,23);ctx.fillRect(-8,-86,33,23);ctx.fillStyle=state.travel?'#fff4ac':'#f9e4a6';ctx.fillRect(70,-31,17,12);ctx.strokeStyle='#28495a';ctx.strokeRect(30,-50,30,50);txt('FIREFLY',12,-17,15,'#fff8d4','center');[-70,-12,43,78].forEach(a=>{ctx.fillStyle='#27343e';ctx.beginPath();ctx.arc(a,3,15,0,7);ctx.fill();ctx.fillStyle='#d8d4bd';ctx.beginPath();ctx.arc(a,3,6,0,7);ctx.fill()});ctx.restore()}
function player(){let p=state.player,x=wx(p.x),walk=p.mode==='walk'?Math.sin(state.t*15)*4:Math.sin(state.t*2),act=p.action;ctx.save();ctx.translate(x,p.y+walk);ctx.scale(p.face,1);if(act)ctx.rotate(-.45*Math.sin(act*7));ctx.fillStyle='#324a55';ctx.fillRect(-15,38+Math.abs(walk),10,11);ctx.fillRect(6,38-Math.abs(walk),10,11);poly([[-17,10],[-22,34],[-13,45],[18,43],[25,24],[15,9]],'#d36b55','#293d49');ctx.fillStyle='#7a4f45';ctx.beginPath();ctx.arc(-20,26,11,0,7);ctx.fill();ctx.fillStyle='#ffd29d';ctx.beginPath();ctx.arc(2,1,18,0,7);ctx.fill();poly([[-20,-1],[-11,-21],[12,-28],[25,-9],[15,-7],[-8,-8]],'#593d57','#293d49');ctx.fillStyle='#263d48';ctx.fillRect(11,2,3,3);ctx.strokeStyle='#f3dec4';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(18,20);ctx.lineTo(44,2);ctx.stroke();ctx.beginPath();ctx.arc(49,-3,14,.4,4.4);ctx.stroke();ctx.restore()}
function tito(){let x=wx(460),y=505+Math.sin(state.t*2)*2;ctx.save();ctx.translate(x,y);poly([[-18,40],[-21,11],[-8,-1],[17,3],[26,39]],'#7c6cad','#343d55');ctx.fillStyle='#f2be91';ctx.beginPath();ctx.arc(1,-12,18,0,7);ctx.fill();poly([[-21,-10],[-7,-34],[18,-28],[26,-4],[10,-13]],'#d86f55','#343d55');ctx.fillStyle='#40585c';ctx.fillRect(-19,40,15,8);ctx.fillRect(10,40,15,8);ctx.restore();txt('TITO',x,y+65,11,'#fff8d9','center')}
function creature(e){let x=wx(e.x),y=e.y+Math.sin(state.t*2+e.phase)*(e.type.includes('fly')||e.type==='bat'?16:3);ctx.save();ctx.translate(x,y);ctx.scale(e.vx<0?-1:1,1);if(e.type==='butterfly'){let w=Math.sin(state.t*13+e.phase)*.45;ctx.fillStyle='#f18b90';ctx.beginPath();ctx.ellipse(-9,0,11,6,w,0,7);ctx.fill();ctx.fillStyle='#f6d078';ctx.beginPath();ctx.ellipse(9,0,11,6,-w,0,7);ctx.fill();ctx.fillStyle='#374658';ctx.fillRect(-2,-6,4,13)}else if(e.type==='frog'){let q=1+Math.sin(state.t*5)*.08;ctx.scale(1,q);ctx.fillStyle='#70ad5f';ctx.beginPath();ctx.ellipse(0,0,18,12,0,0,7);ctx.fill();ctx.beginPath();ctx.arc(-10,-8,6,0,7);ctx.arc(9,-8,6,0,7);ctx.fill();ctx.fillStyle='#273c42';ctx.fillRect(-11,-10,3,3);ctx.fillRect(8,-10,3,3)}else if(e.type==='lizard'||e.type==='mouse'){ctx.fillStyle=e.type==='mouse'?'#9b8275':'#6fae89';ctx.beginPath();ctx.ellipse(0,0,22,7,0,0,7);ctx.fill();ctx.beginPath();ctx.moveTo(-15,1);ctx.lineTo(-39,10);ctx.lineTo(-23,4);ctx.fill();ctx.fillStyle='#233f41';ctx.fillRect(14,-3,3,3)}else if(e.type==='spider'){ctx.strokeStyle='#273442';ctx.lineWidth=3;for(let i=-1;i<2;i+=2)for(let j=0;j<3;j++){ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(i*(11+j*3),-5+j*7);ctx.stroke()}ctx.fillStyle='#474356';ctx.beginPath();ctx.arc(0,0,9,0,7);ctx.fill()}else if(e.type==='bat'){ctx.fillStyle='#4b4969';ctx.beginPath();ctx.moveTo(0,0);ctx.quadraticCurveTo(-17,-15,-28,5);ctx.quadraticCurveTo(-12,1,0,8);ctx.quadraticCurveTo(15,-14,28,5);ctx.quadraticCurveTo(11,1,0,0);ctx.fill()}else{let r=e.type==='rare'||e.type==='cavefly';ctx.shadowColor=r?'#c88fff':'#ffe86f';ctx.shadowBlur=r?24:15;ctx.fillStyle=r?'#d6a2ff':'#f3dc68';ctx.beginPath();ctx.ellipse(0,0,7,5,0,0,7);ctx.fill();ctx.fillStyle='#eaf7d1';ctx.beginPath();ctx.ellipse(-6,-3,7,3,-.5,0,7);ctx.ellipse(6,-3,7,3,.5,0,7);ctx.fill();ctx.shadowBlur=0}ctx.restore()}
function update(dt){state.t+=dt;state.clock=(state.clock+dt/180)%1;ui.time.textContent=state.clock>.22&&state.clock<.78?'DIA':'NOITE';let p=state.player,dir=(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0),run=keys.has('Shift');p.vx+=(dir*(run?900:580)-p.vx)*Math.min(1,dt*7);let max=state.map==='village'?1160:state.map==='forest'?2200:1600;p.x=clamp(p.x+p.vx*dt,50,max);if(dir)p.face=dir;p.mode=Math.abs(p.vx)>20?'walk':'idle';p.action=Math.max(0,p.action-dt*2.5);state.camera.target=clamp(p.x-W*.46,0,Math.max(0,max-W+100));state.camera.x+=(state.camera.target-state.camera.x)*Math.min(1,dt*4);state.camera.shake*=.82;for(const e of state.entities){if(!e.alive)continue;let d=Math.abs(e.x-p.x),night=state.clock<.22||state.clock>.78;if((e.type==='firefly'||e.type==='rare')&&!night&&state.map==='forest'){e.mode='idle';continue}if(d<150&&(!e.type.includes('fly'))){e.mode='flee';e.vx+=(Math.sign(e.x-p.x)*((e.type==='lizard'?200:110))-e.vx)*dt*5}else{e.mode='wander';e.vx+=(Math.sin(state.t+e.phase)*35-e.vx)*dt}e.x=clamp(e.x+e.vx*dt,20,max-20)}if(state.fishing){state.fishing.time-=dt;if(state.fishing.time<=0&&!state.fishing.ready){state.fishing.ready=true;notify('A boia afundou! Aperte ESPAÇO!');AudioManager.playSFX('fish')}else if(state.fishing.ready&&state.fishing.time<-1.8){state.fishing=null;notify('O peixe escapou. Tente de novo.')}}if(state.travel){state.travel-=dt;if(state.travel<.65)addParticles(890,state.player.y,'#d9ded0',2);if(state.travel<=0){AudioManager.playSFX('van-engine');beginMap('forest',170)}}for(let i=state.particles.length-1;i>=0;i--){let q=state.particles[i];q.life-=dt;q.x+=q.vx*60*dt;q.y+=q.vy*60*dt;q.vy+=1.2*dt;if(q.life<=0)state.particles.splice(i,1)}if(state.fade.job){state.fade.value+=dt*1.9;if(state.fade.value>=1&&state.fade.job){let j=state.fade.job;state.fade.job=null;j()}else if(!state.fade.job&&state.fade.value>0)state.fade.value-=dt*1.9}}
function render(){ctx.save();ctx.translate((Math.random()-.5)*state.camera.shake,(Math.random()-.5)*state.camera.shake);sky();ground();if(state.map==='village'){[130,280,780,1120].forEach((x,i)=>tree(x,320,i%2?.85:1,i%2));house();van();tito();for(let x=80;x<1180;x+=73)flower(x,544,x%2?'#f59b86':'#f4d477')}else if(state.map==='forest'){[90,270,480,1120,1300,1500,1730,1920,2110].forEach((x,i)=>tree(x,315,.75+(i%3)*.17,i%2));lake();caveEntrance();for(let x=160;x<2200;x+=87)flower(x,550,x%2?'#f0928d':'#e6d46e');state.entities.filter(e=>e.alive).forEach(creature)}else{caveWorld();state.entities.filter(e=>e.alive).forEach(creature)}player();for(const q of state.particles){ctx.globalAlpha=q.life;ctx.fillStyle=q.color;ctx.fillRect(wx(q.x),q.y,q.size,q.size);ctx.globalAlpha=1}if(state.map==='cave'){let x=wx(state.player.x),r=save.inventory.lantern?190:110;ctx.save();ctx.fillStyle='#071221dd';ctx.fillRect(0,0,W,H);ctx.globalCompositeOperation='destination-out';let g=ctx.createRadialGradient(x,state.player.y,15,x,state.player.y,r);g.addColorStop(0,'#000');g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,state.player.y,r,0,7);ctx.fill();ctx.restore()}ctx.restore();let o=activeInteractable();ui.prompt.textContent=o?'[E] '+o.label:(state.map==='forest'?'[ESPAÇO] usar rede':'Explore com calma');if(o){ctx.fillStyle='#173f43dd';ctx.beginPath();ctx.roundRect(wx(o.x)-62,o.y-75,124,26,8);ctx.fill();txt('[E] '+o.label,wx(o.x),o.y-57,11,'#fff8d7','center')}let q=quest();if(q.status==='active'||q.status==='complete'){ctx.fillStyle='#173f43dd';ctx.beginPath();ctx.roundRect(20,100,170,52,10);ctx.fill();txt('MISSÃO · TITO',32,120,11,'#fbe7a7');txt(q.status==='complete'?'✓ Volte para Tito':'Sapos: '+q.progress+' / 3',32,140,13,'#fff')}if(state.fade.value>0){ctx.globalAlpha=Math.min(1,state.fade.value);ctx.fillStyle='#102630';ctx.fillRect(0,0,W,H);ctx.globalAlpha=1}}
let last=0;function loop(now){let dt=Math.min(.033,(now-last)/1000||0);last=now;update(dt);render();requestAnimationFrame(loop)}
function panel(kind){let body='';if(kind==='bag'){let rows=[...Object.entries(save.inventory),...Object.entries(save.catches)].filter(([,n])=>n>0);body=rows.length?rows.map(([id,n])=>`<div class="card"><div><b>${names[id]||({bait:'Isca simples',reinforcedNet:'Rede reforçada',lantern:'Lanterna',explorationKit:'Kit de exploração'})[id]}</b><small>Quantidade: ${n}</small></div></div>`).join(''):'<p>A mochila está vazia.</p>';ui.panel.innerHTML=`<button class="close">×</button><h2 class="panel-title">Mochila</h2>${body}`}if(kind==='book'){body=Object.keys(names).map(id=>`<div class="card"><div><b>${save.discovered[id]?names[id]:'???'}</b><small>${save.discovered[id]?rarity[id]:'continue explorando'}</small></div></div>`).join('');ui.panel.innerHTML=`<button class="close">×</button><h2 class="panel-title">Bestiário</h2>${body}`}if(kind==='quest'){let q=quest();ui.panel.innerHTML=`<button class="close">×</button><h2 class="panel-title">Missões</h2><div class="card"><div><b>${QUESTS.tito_frogs.title}</b><small>${q.status==='available'?'Fale com Tito':q.status==='claimed'?'Concluída':q.progress+' / 3 sapos'}</small><div class="bar"><i style="width:${q.status==='claimed'?100:q.progress/3*100}%"></i></div></div></div>`}ui.panel.classList.remove('hidden');ui.panel.querySelector('.close').onclick=()=>ui.panel.classList.add('hidden')}
addEventListener('keydown',e=>{AudioManager.unlock();keys.add(e.key);if([' ','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();if(e.key===' '){if(state.fishing?.ready)finishFishing();else capture()}if(e.key==='e'||e.key==='E'){if(!ui.dialog.classList.contains('hidden'))return;let o=activeInteractable();o?o.onInteract():null}if(e.key==='i'||e.key==='I')panel('bag');if(e.key==='b'||e.key==='B')panel('book');if(e.key==='m'||e.key==='M')panel('quest');if(e.key==='n'||e.key==='N'){state.clock=(state.clock+.5)%1;notify('O tempo avançou.')}});addEventListener('keyup',e=>keys.delete(e.key));document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>panel(b.dataset.panel));$('#mute').onclick=()=>AudioManager.toggle();buildMap();saveGame();requestAnimationFrame(loop);
