const defaultState={area:'village',coins:25,items:{'Borboleta':0,'Sapo':0,'Lagartixa':0,'Aranha':0,'Vagalume':0,'Vagalume raro':0,'Peixe-lua':0,'Peixe-listrado':0},day:true,playerX:31};
const savedState=JSON.parse(sessionStorage.getItem('firefly-state')||'null');
const state=savedState?{...defaultState,...savedState,items:{...defaultState.items,...savedState.items}}:defaultState;
function saveState(){sessionStorage.setItem('firefly-state',JSON.stringify(state));}
document.querySelector('#coins').textContent=state.coins;
const world=document.querySelector('#world'); let player=document.querySelector('#player'); const toast=document.querySelector('#toast'),panel=document.querySelector('#sidePanel'),content=document.querySelector('#panelContent');
const creatures=[['butterfly','🦋','Borboleta','Comum'],['frog','🐸','Sapo','Comum'],['lizard','🦎','Lagartixa','Comum'],['spider','🕷️','Aranha','Noturno'],['firefly','✨','Vagalume','Brilha à noite'],['rare','🌟','Vagalume raro','Raro']];
function notify(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
function setPlayer(x){state.playerX=Math.max(3,Math.min(91,x));player.style.left=state.playerX+'%';}
function forest(){state.area='forest';world.className='world forest';world.innerHTML=`<div class="sky-decor"><i class="cloud c1"></i><i class="cloud c2"></i><i class="sun"></i></div><div id="sceneLabel" class="scene-label"><span>🌲</span><div><b>FLORESTA CINTILANTE</b><small>onde até as pedras têm segredos</small></div></div><div class="tree t1"></div><div class="tree t2"></div><div class="tree t3"></div><div class="pond"></div><div class="cave"></div><div class="ground"></div><button class="return-village">← Voltar para a Vila</button><div class="player" id="player"><span class="net">⌒</span><span class="player-head">🙂</span><span class="player-body"></span></div><div class="hint" id="worldHint">Ande, explore e capture! <b>ESPAÇO</b> usa a rede</div>`;
 player=document.querySelector('#player');setPlayer(31);creatures.forEach(([cl,icon,name,rarity])=>{const el=document.createElement('div');el.className='creature '+cl;el.dataset.name=name;el.innerHTML=`<span>${icon}</span><label>${name}</label>`;el.onclick=()=>capture(el,name,rarity);world.append(el)});document.querySelector('.return-village').onclick=village;notify('Chegamos! A floresta parece estar piscando para você.');}
function village(){state.area='village';saveState();location.reload()}
function capture(el,name,rarity){if(state.area!=='forest')return;state.items[name]++;el.remove();saveState();notify(`✨ ${name} capturado! Adicionado ao bestiário.`);if(name==='Sapo'&&state.items[name]===3){state.coins+=15;document.querySelector('#coins').textContent=state.coins;saveState();notify('Missão completa! +15 moedas');}}
function renderPanel(type){panel.classList.add('open');document.querySelectorAll('.hud-item').forEach(x=>x.classList.toggle('active',x.dataset.panel===type));const captured=Object.entries(state.items).filter(([,n])=>n);if(type==='bag')content.innerHTML=`<button class="close-panel">×</button><h2 class="panel-title">Mochila</h2><p class="panel-subtitle">Tudo que cabe entre uma bolacha e uma bússola.</p>${captured.length?captured.map(([n,q])=>`<div class="item-card"><span>✦</span><div><b>${n}</b><small>coletado na Floresta</small></div><strong class="rarity">× ${q}</strong></div>`).join(''):'<div class="item-card"><span>🎒</span><div><b>Ainda está vazia</b><small>Explore a floresta para enchê-la!</small></div></div>'}`;
if(type==='book')content.innerHTML=`<button class="close-panel">×</button><h2 class="panel-title">Bestiário</h2><p class="panel-subtitle">Criaturas vistas: ${captured.length}/6</p>${['Borboleta','Sapo','Lagartixa','Aranha','Vagalume','Vagalume raro'].map(n=>`<div class="item-card"><span>${state.items[n]?'✦':'?'}</span><div><b>${state.items[n]?n:'???'}</b><small>${state.items[n]?`Capturados: ${state.items[n]}`:'Continue explorando...'}</small></div></div>`).join('')}`;
if(type==='quest')content.innerHTML=`<button class="close-panel">×</button><h2 class="panel-title">Missões</h2><p class="panel-subtitle">Tito acredita em você. Estranhamente.</p><div class="item-card"><span>🐸</span><div><b>O coro da lagoa</b><small>Capture 3 sapos</small><div class="progress"><i style="width:${Math.min(100,state.items['Sapo']*33)}%"></i></div><small>${state.items['Sapo']}/3 · recompensa: 15 ✦</small></div></div><div class="item-card"><span>🌟</span><div><b>Luz de bolso</b><small>Encontre um vagalume raro</small><div class="progress"><i style="width:${state.items['Vagalume raro']?100:0}%"></i></div></div></div>`;
content.querySelector('.close-panel').onclick=()=>panel.classList.remove('open');}
document.querySelectorAll('.hud-item').forEach(b=>b.onclick=()=>renderPanel(b.dataset.panel));document.querySelector('#closePanel').onclick=()=>panel.classList.remove('open');
function toggleDay(){state.day=!state.day;world.classList.toggle('night',!state.day);notify(state.day?'☀️ O sol voltou a sorrir.':'🌙 A noite trouxe pequenos brilhos.');}
document.querySelector('#soundBtn').onclick=toggleDay;document.querySelector('#helpBtn').onclick=()=>notify('A, D ou setas: andar · Espaço: rede · E: usar van');document.querySelector('#van').onclick=()=>document.querySelector('#travelModal').classList.remove('hidden');document.querySelector('#npc').onclick=()=>document.querySelector('#dialogModal').classList.remove('hidden');document.querySelectorAll('.modal-close').forEach(b=>b.onclick=()=>b.closest('.modal').classList.add('hidden'));document.querySelector('#forestBtn').onclick=()=>{document.querySelector('#travelModal').classList.add('hidden');forest()};
document.addEventListener('keydown',e=>{if(['ArrowLeft','a','A'].includes(e.key))setPlayer(state.playerX-4);if(['ArrowRight','d','D'].includes(e.key))setPlayer(state.playerX+4);if(e.key==='e'||e.key==='E'){if(state.area==='village')document.querySelector('#travelModal').classList.remove('hidden')}if(e.key===' '&&state.area==='forest'){const all=[...document.querySelectorAll('.creature')];if(all.length){const target=all.reduce((best,x)=>{const rect=x.getBoundingClientRect(),pr=player.getBoundingClientRect();return Math.abs(rect.x-pr.x)<Math.abs(best.getBoundingClientRect().x-pr.x)?x:best});capture(target,target.dataset.name,'')}}if(e.key==='i'||e.key==='I')renderPanel('bag');if(e.key==='b'||e.key==='B')renderPanel('book');if(e.key==='m'||e.key==='M')renderPanel('quest');});
