/* =========================================================
   CRIATURAS 3.2 — comportamento orgânico + interações
   ========================================================= */
import {rnd,clamp,pick,chance} from '../core/utils.js';
import {state} from '../core/state.js';
import {rarity,SPECIES} from '../data/game-data.js';
import {wx} from '../render/draw-helpers.js';
import {LAKE,FOREST_ROCKS,forestFlowerSpots} from '../world/spots.js';
export function spawn(type,x,y,options={}){state.entities.push({type,x,y,homeX:x,homeY:y,vx:0,vy:0,phase:rnd(0,6),timer:rnd(.4,2),orbitAngle:rnd(0,6.28),aiState:'idle',alive:true,visible:true,rarity:rarity[type],look:Math.random(),mood:'calm',...options});}
export function spawnForest(){[['butterfly',720,390],['butterfly',980,350],['butterfly',1260,370],['butterfly',1420,330],['frog',1530,510],['frog',1710,520],['frog',1920,505],['frog',2160,515],['lizard',2670,475],['lizard',3010,470],['lizard',3270,485],['spider',3480,470],['spider',3650,500],['firefly',1880,360],['firefly',2010,345],['firefly',2250,370],['rare',4540,350],['rare',4860,330]].forEach(c=>spawn(...c));}
export function spawnCave(){[['bat',480,235],['bat',900,265],['bat',1510,220],['bat',2180,250],['spider',600,500],['spider',1120,485],['spider',1770,520],['spider',2650,500],['mouse',820,535],['mouse',1420,545],['mouse',2490,530],['mouse',3160,545],['cavefly',1560,360],['cavefly',2240,390],['rare',2920,330]].forEach(c=>spawn(...c));}
export function updateCreature(e,dt,world){if(!e.alive)return;const s=SPECIES[e.type]||SPECIES.butterfly;e.timer-=dt;if(s.nightOnly&&!world.isNight){e.aiState='hidden';e.visible=false;e.vx*=Math.max(0,1-dt*8);return;}e.visible=true;const social=nearbyCreatures(e,world.entities||[]);if(s.sleeper){updateBat(e,dt,world,s,social);return;}const d=Math.hypot(e.x-world.playerX,e.y-(world.playerY??e.y));if(!s.swarm&&d<s.fleeDistance){e.aiState='flee';e.mood='alert';const dx=e.x-world.playerX,dy=e.y-(world.playerY??e.y),len=Math.max(1,Math.hypot(dx,dy));e.vx+=(dx/len*s.fleeSpeed-e.vx)*Math.min(1,dt*8);e.vy+=(dy/len*s.fleeSpeed-e.vy)*Math.min(1,dt*8);e.x=clamp(e.x+e.vx*dt,30,world.maxX-30);e.y=clamp(e.y+e.vy*dt,330,590);return;}if(e.aiState==='flee')e.mood='calm';switch(e.type){case'butterfly':return updateButterfly(e,dt,world,s,social);case'frog':return updateFrog(e,dt,world,s,social);case'lizard':return updateLizard(e,dt,world,s,social);case'spider':return updateSpider(e,dt,world,s,social);case'mouse':return updateMouse(e,dt,world,s,social);default:return updateSwarm(e,dt,world,s,social);}}
function nearbyCreatures(e,all){return all.filter(o=>o!==e&&o.alive&&o.visible&&Math.abs(o.x-e.x)<180&&Math.abs(o.y-e.y)<120);}
function updateButterfly(e,dt,world,s,social){const flower=pickNearbyFlower(e.x);const fireflies=social.filter(o=>o.type==='firefly');if(e.aiState==='landed'){e.vx*=Math.max(0,1-dt*14);e.y=e.homeY+7;if(e.timer<=0){e.aiState='seek';e.timer=rnd(1.5,3.5);}return;}if(e.targetX===undefined||e.timer<=0){e.aiState='seek';e.targetX=flower;e.timer=rnd(1.8,3.8);}const dx=e.targetX-e.x;e.vx+=(Math.sign(dx)*s.wanderSpeed*1.5-e.vx)*Math.min(1,dt*3);e.x=clamp(e.x+e.vx*dt,30,world.maxX-30);e.y=e.homeY+Math.sin(state.t*2.3+e.phase)*15;if(Math.abs(dx)<18){e.aiState='landed';e.timer=rnd(2,5);e.vx=0;}if(fireflies.length&&world.isNight){e.mood='curious';e.x+=Math.sin(state.t+e.phase)*dt*4;}}
function pickNearbyFlower(x){const spots=forestFlowerSpots().filter(v=>Math.abs(v-x)<500);return spots.length?pick(spots):x+rnd(-160,160);}
function updateFrog(e,dt,world,s,social){const minX=LAKE.x-LAKE.radius+30,maxX=LAKE.x+LAKE.radius-30;if(e.aiState==='jump'){e.vy+=360*dt;e.x+=e.vx*dt;e.y+=e.vy*dt;if(e.timer<=0){e.y=clamp(e.y,480,555);e.vy=0;e.vx=0;e.aiState='rest';e.timer=rnd(.5,1.8);}return;}const rain=world.event?.id==='frog_rain';if(rain){e.mood='excited';e.timer=Math.min(e.timer,.45);if(e.timer<=0){e.aiState='jump';e.timer=.62;e.vy=-190;e.vx=rnd(-45,45);return;}}if(e.timer<=0&&chance(world.isNight?.055:.025)){e.aiState='jump';e.timer=.62;e.vy=-175;e.vx=rnd(-35,35);return;}const leader=social.find(o=>o.type==='frog'&&Math.abs(o.x-e.x)>30);const follow=leader?Math.sign(leader.x-e.x)*s.wanderSpeed*.35:0;const targetSpeed=(world.isNight?1.55:1)*s.wanderSpeed;e.vx+=(Math.sin(state.t*.65+e.phase)*targetSpeed+follow-e.vx)*Math.min(1,dt*2);e.x=clamp(e.x+e.vx*dt,minX,maxX);e.y+=Math.sin(state.t*2+e.phase)*.08;e.aiState='wander';}
function updateLizard(e,dt,world,s,social){const warm=social.some(o=>o.type==='lizard');if(e.aiState==='dart'){e.x=clamp(e.x+e.vx*dt,30,world.maxX-30);e.vx*=Math.max(0,1-dt*4);if(e.timer<=0){e.vx=0;e.aiState='sun';e.timer=rnd(2.5,6);}return;}if(e.timer<=0){const rock=FOREST_ROCKS.reduce((a,r)=>Math.abs(r.x-e.x)<Math.abs(a.x-e.x)?r:a);e.vx=(clamp(rock.x+rnd(-35,35),30,world.maxX-30)-e.x)*2.2;e.aiState='dart';e.timer=.45;}else{e.aiState='sun';if(warm)e.mood='social';}}
function updateSpider(e,dt){e.vx*=Math.max(0,1-dt*12);e.vy*=Math.max(0,1-dt*12);if(e.webX===undefined){e.webX=e.x;e.webTop=e.homeY-82;e.webBottom=e.homeY+18;e.webT=rnd(0,1);}if(e.aiState==='web-down'||e.aiState==='web-up'){e.webT=clamp(e.webT+(e.aiState==='web-down'?1:-1)*dt*.35,0,1);e.y=e.webTop+(e.webBottom-e.webTop)*e.webT;e.x=e.webX+Math.sin(state.t*1.8+e.phase)*3;if(e.webT<=0||e.webT>=1){e.aiState='web-rest';e.timer=rnd(1.5,4);}return;}e.aiState='web-rest';e.x=e.webX+Math.sin(state.t*.7+e.phase)*2;if(e.timer<=0){e.aiState=chance(.5)?'web-down':'web-up';}}
function updateMouse(e,dt,world,s,social){const spider=social.find(o=>o.type==='spider');if(spider&&Math.abs(spider.x-e.x)<130){e.aiState='skitter';e.mood='alert';e.vx=(e.x<spider.x?-1:1)*s.wanderSpeed*2.4;e.timer=.55;}if(e.aiState==='skitter'){e.x=clamp(e.x+e.vx*dt,30,world.maxX-30);e.y=525+Math.sin(state.t*7+e.phase)*3;if(e.timer<=0){e.vx=0;e.aiState='pause';e.mood='calm';e.timer=rnd(1,2.5);}return;}if(e.timer<=0){e.aiState='skitter';e.timer=rnd(.35,.8);e.vx=pick([-1,1])*s.wanderSpeed*1.8;}}
function updateSwarm(e,dt,world,s,social){e.aiState='swarm';e.orbitAngle+=dt*(s.wanderSpeed/55);const companion=social.find(o=>o.type===e.type);const r=e.type==='rare'?85:42;e.x=clamp(e.homeX+Math.cos(e.orbitAngle)*r,30,world.maxX-30);e.y=e.homeY+Math.sin(e.orbitAngle*1.25)*r*.42;if(companion){e.x+=(companion.x-e.x)*dt*.015;e.y+=(companion.y-e.y)*dt*.015;}}
function updateBat(e,dt,world,s,social){const d=Math.hypot(e.x-world.playerX,e.y-(world.playerY??e.y));if(e.aiState==='sleeping'||!e.aiState){e.aiState='sleeping';e.vx=0;if(d<s.fleeDistance||world.isNight&&chance(.002)){e.aiState='waking';e.timer=.55;}return;}if(e.aiState==='waking'){e.y=e.homeY+Math.sin(state.t*10)*4;if(e.timer<=0){e.aiState='flying';e.timer=rnd(3,6);e.orbitAngle=rnd(0,6.28);}return;}if(e.aiState==='flying'){const flock=social.filter(o=>o.type==='bat').length;e.orbitAngle+=dt*(2.1+Math.min(1,flock*.08));e.x=clamp(e.homeX+Math.cos(e.orbitAngle)*120,30,world.maxX-30);e.y=e.homeY+40+Math.sin(e.orbitAngle*1.8)*38;if(e.timer<=0){e.aiState='returning';e.timer=1.5;}return;}e.x+=(e.homeX-e.x)*Math.min(1,dt*2.3);e.y+=(e.homeY-e.y)*Math.min(1,dt*2.3);if(e.timer<=0||Math.abs(e.x-e.homeX)<4){e.aiState='sleeping';e.x=e.homeX;e.y=e.homeY;}}
function eye(ctx,x,y,r=2){ctx.fillStyle='#182c32';ctx.beginPath();ctx.arc(x,y,r,0,6.28);ctx.fill();}function body(ctx,c,x,y,rx,ry){ctx.fillStyle=c;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,6.28);ctx.fill();}function limb(ctx,a,b,c,d,w=2){ctx.strokeStyle='#34454b';ctx.lineWidth=w;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(a,b);ctx.lineTo(c,d);ctx.stroke();}
export function drawCreature(e,ctx,t){if(!e.visible)return;const x=wx(e.x);ctx.save();ctx.translate(x,e.y);if(e.vx<0)ctx.scale(-1,1);if(e.type==='butterfly'){const flap=e.aiState==='landed'?.05:Math.sin(t*15+e.phase)*.5;ctx.strokeStyle='#39434a';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-8);ctx.lineTo(0,8);ctx.stroke();ctx.save();ctx.rotate(flap);body(ctx,'#e9a2aa',-9,-2,10,7);ctx.restore();ctx.save();ctx.rotate(-flap);body(ctx,'#f2ca79',9,-2,10,7);ctx.restore();body(ctx,'#805565',0,1,3,9);}else if(e.type==='frog'){const sq=e.aiState==='jump'?1.18:1+Math.sin(t*5)*.025;ctx.scale(1,sq);body(ctx,'#68a962',0,1,19,12);body(ctx,'#88bd72',-9,-7,7,7);body(ctx,'#88bd72',9,-7,7,7);eye(ctx,-9,-9,2);eye(ctx,9,-9,2);ctx.strokeStyle='#345444';ctx.beginPath();ctx.arc(0,2,8,.15,2.9);ctx.stroke();limb(ctx,-13,8,-21,15);limb(ctx,13,8,21,15);}else if(e.type==='lizard'){body(ctx,'#719e73',0,1,21,7);ctx.fillStyle='#4e785c';ctx.beginPath();ctx.moveTo(-13,1);ctx.quadraticCurveTo(-29,5,-42,11);ctx.quadraticCurveTo(-27,0,-16,-5);ctx.fill();body(ctx,'#88b47e',15,-3,8,6);eye(ctx,18,-5,1.8);limb(ctx,-8,4,-16,10,2);limb(ctx,8,4,16,10,2);}else if(e.type==='spider'){const hanging=e.webX!==undefined;const top=e.webTop??(e.homeY-82);if(hanging){ctx.strokeStyle='#dce2d5aa';ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(0,top-e.y);ctx.lineTo(0,0);ctx.stroke();}const legWave=Math.sin(t*5+e.phase)*3;for(let i=0;i<4;i++){const yy=-4+i*5;limb(ctx,0,yy,-13-i*2,yy-7+legWave,2);limb(ctx,0,yy,13+i*2,yy-7-legWave,2);}body(ctx,'#4a485a',0,1,11,9);body(ctx,'#343442',0,9,8,6);eye(ctx,-3,-1,1.5);eye(ctx,3,-1,1.5);}else if(e.type==='mouse'){body(ctx,'#9b8178',0,1,15,9);ctx.fillStyle='#b9918c';ctx.beginPath();ctx.arc(-9,-8,6,0,6.28);ctx.arc(7,-8,6,0,6.28);ctx.fill();eye(ctx,10,-2,1.6);limb(ctx,-14,5,-24,7,1.5);}else if(e.type==='bat'){const flap=e.aiState==='flying'?Math.sin(t*18)*10:0;ctx.fillStyle='#4d4968';ctx.beginPath();ctx.moveTo(0,3);ctx.quadraticCurveTo(-14,-17-flap,-32,1);ctx.quadraticCurveTo(-26,14,-11,8);ctx.quadraticCurveTo(0,14,11,8);ctx.quadraticCurveTo(26,14,32,1);ctx.quadraticCurveTo(14,-17-flap,0,3);ctx.fill();body(ctx,'#5d5370',0,2,7,10);eye(ctx,-2,-1,1.2);eye(ctx,2,-1,1.2);}else{const rare=e.type==='rare'||e.type==='cavefly';ctx.shadowColor=rare?'#c99bff':'#ffe47a';ctx.shadowBlur=rare?32:19;body(ctx,rare?'#d9adff':'#f4dd70',0,0,6,4);ctx.shadowBlur=0;ctx.fillStyle='#eef7d8';ctx.globalAlpha=.7;ctx.beginPath();ctx.ellipse(-7,-3,8,3,-.5,0,6.28);ctx.ellipse(7,-3,8,3,.5,0,6.28);ctx.fill();ctx.globalAlpha=1;}ctx.restore();}
