/* FireFly 4.1 — wildlife expansion */
import {state} from '../core/state.js';
import {SPECIES_2,REGION_SPAWNS,VARIANTS} from '../data/capture-2-data.js';
import {isNight} from '../core/state.js';
import {weatherType} from './weather.js';
import {wx} from '../render/draw-helpers.js';

const RANGES={entrance:[120,580],flower:[680,1380],lagoon:[1520,2380],oldTrail:[2520,3340],quarry:[3480,4140],highGrove:[4280,5050],mouth:[180,600],echo:[700,1380],crystal:[1500,2380],deep:[2520,3500]};
export function currentCaptureRegion(){const x=state.player.x;const ranges=state.map==='cave'?['mouth','echo','crystal','deep']:['entrance','flower','lagoon','oldTrail','quarry','highGrove'];return ranges.find(id=>x>=RANGES[id][0]&&x<=RANGES[id][1])||ranges[0];}
function conditionAllowed(d,region){if(d.maps&&!d.maps.includes(state.map))return false;if(d.regions&&!d.regions.includes(region))return false;const night=isNight();if(d.time==='night'&&!night)return false;if(d.time==='day'&&night)return false;const w=weatherType();if(state.map!=='cave'&&d.weather?.length&&!d.weather.includes(w))return false;return true;}
function pickVariant(d){if(!d.variants?.length)return null;const id=d.variants[Math.floor(Math.random()*d.variants.length)];return {id,name:VARIANTS[id]?.name||id,multiplier:VARIANTS[id]?.multiplier||1};}
export function spawnRegionalWildlife(){const region=currentCaptureRegion();const types=REGION_SPAWNS[region]||[];const existing=state.entities.filter(e=>e.capture2&&e.alive).length;if(existing>14)return;const range=RANGES[region];types.slice(0,5).forEach((type,index)=>{if(state.entities.some(e=>e.capture2&&e.type===type&&Math.abs(e.x-state.player.x)<240))return;const d=SPECIES_2[type];if(!d||!conditionAllowed(d,region))return;const span=Math.max(80,range[1]-range[0]);const x=Math.max(range[0],Math.min(range[1],state.player.x-160+((index*137)%span)));const y=type==='bat'||type==='owl'?300+(index%3)*22:type==='firefly'||type==='glowmoth'?350+(index%2)*30:type==='crystalbug'?520:510;const variant=pickVariant(d);state.entities.push({type,x,y,homeX:x,homeY:y,vx:0,vy:0,phase:Math.random()*6,timer:.5+Math.random()*2,orbitAngle:Math.random()*6.28,aiState:'idle',alive:true,visible:true,rarity:d.rarity,mood:'calm',capture2:true,variant,captureDifficulty:d.baseDifficulty});});}
export function updateRegionalWildlife(dt){const region=currentCaptureRegion();const w=weatherType();for(const e of state.entities.filter(v=>v.capture2&&v.alive)){const d=SPECIES_2[e.type];if(!d)continue;if(!conditionAllowed(d,region)){e.visible=false;e.vx*=Math.max(0,1-dt*8);continue;}e.visible=true;const distance=Math.abs(e.x-state.player.x);if(distance<65){e.mood='alert';e.aiState='flee';const dir=e.x>=state.player.x?1:-1;e.vx=dir*(e.type==='deer'?150:e.type==='otter'?120:e.type==='owl'?110:95);e.x+=e.vx*dt;continue;}e.mood='calm';if(e.type==='otter'){e.aiState='dive';e.x=e.homeX+Math.sin(state.t*.65+e.phase)*85;e.y=510+Math.sin(state.t*1.4+e.phase)*13;}else if(e.type==='deer'){e.aiState='graze';e.x=e.homeX+Math.sin(state.t*.22+e.phase)*55;e.y=505;}else if(e.type==='owl'){e.aiState='perch';e.x=e.homeX+Math.sin(state.t*.45+e.phase)*45;e.y=320+Math.sin(state.t*.9+e.phase)*12;}else if(e.type==='crystalbug'){e.aiState='crawl';e.x=e.homeX+Math.sin(state.t*.8+e.phase)*32;e.y=520+Math.sin(state.t*2+e.phase)*3;}else if(e.type==='glowmoth'){e.aiState='orbit';e.orbitAngle+=dt*1.5;e.x=e.homeX+Math.cos(e.orbitAngle)*50;e.y=e.homeY+Math.sin(e.orbitAngle)*18;}else if(e.type==='spider'){e.aiState='web';e.x=e.homeX+Math.sin(state.t*.3+e.phase)*10;}else if(e.type==='bat'){e.aiState='flight';e.orbitAngle+=dt*1.8;e.x=e.homeX+Math.cos(e.orbitAngle)*90;e.y=e.homeY+Math.sin(e.orbitAngle*1.4)*35;}else if(e.type==='mouse'){e.aiState='skitter';e.x=e.homeX+Math.sin(state.t*1.2+e.phase)*35;e.y=525+Math.sin(state.t*4+e.phase)*3;}else{e.aiState='wander';e.x=e.homeX+Math.sin(state.t*.7+e.phase)*35;e.y=e.homeY+Math.sin(state.t*1.7+e.phase)*7;}if(w==='cave')e.mood=e.type==='bat'?'alert':'calm';}}
export function drawRegionalWildlife(e,ctx,t){if(!e.capture2||!e.visible)return false;const x=wx(e.x);ctx.save();ctx.translate(x,e.y);if(e.vx<0)ctx.scale(-1,1);const flap=Math.sin(t*9+e.phase);if(e.type==='otter'){ctx.fillStyle=e.variant?.id==='moon'?'#a8a0b9':'#8b6557';ctx.beginPath();ctx.ellipse(0,0,25,10,0,0,6.28);ctx.fill();ctx.fillStyle='#b78970';ctx.beginPath();ctx.arc(21,-5,8,0,6.28);ctx.fill();ctx.strokeStyle='#b8dce2';ctx.lineWidth=2;ctx.beginPath();ctx.arc(-5,10,25,0,3.2);ctx.stroke();}else if(e.type==='deer'){ctx.fillStyle=e.variant?.id==='white'?'#e7e0d1':'#8b715d';ctx.beginPath();ctx.ellipse(0,0,23,12,0,0,6.28);ctx.fill();ctx.fillRect(14,-28,8,28);ctx.beginPath();ctx.arc(19,-31,9,0,6.28);ctx.fill();ctx.strokeStyle='#d4b998';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(15,-38);ctx.lineTo(7,-50);ctx.moveTo(21,-38);ctx.lineTo(29,-50);ctx.stroke();}else if(e.type==='owl'){ctx.fillStyle=e.variant?.id==='moon'?'#a8a0c7':'#52667a';ctx.beginPath();ctx.arc(0,0,17,0,6.28);ctx.fill();ctx.fillStyle='#d9c994';ctx.beginPath();ctx.arc(-7,-3,6,0,6.28);ctx.arc(7,-3,6,0,6.28);ctx.fill();ctx.fillStyle='#202d37';ctx.beginPath();ctx.arc(-7,-3,2,0,6.28);ctx.arc(7,-3,2,0,6.28);ctx.fill();ctx.fillStyle='#d99b62';ctx.beginPath();ctx.moveTo(0,2);ctx.lineTo(-4,8);ctx.lineTo(4,8);ctx.closePath();ctx.fill();}else if(e.type==='crystalbug'){ctx.fillStyle=e.variant?.id==='amber'?'#e3ae5e':'#6acbd0';ctx.beginPath();ctx.ellipse(0,0,14,9,0,0,6.28);ctx.fill();ctx.fillStyle='#d8ffff';ctx.beginPath();ctx.arc(-6,-3,3,0,6.28);ctx.arc(6,-3,3,0,6.28);ctx.fill();}else if(e.type==='glowmoth'){ctx.shadowColor=e.variant?.id==='pearl'?'#f2e8ff':'#d3a7ff';ctx.shadowBlur=20;ctx.fillStyle=e.variant?.id==='pearl'?'#f2e8ff':'#d3a7ff';ctx.beginPath();ctx.ellipse(-10,flap*3,12,7,-.45,0,6.28);ctx.ellipse(10,-flap*3,12,7,.45,0,6.28);ctx.fill();ctx.fillStyle='#6b527e';ctx.beginPath();ctx.ellipse(0,0,3,9,0,0,6.28);ctx.fill();ctx.shadowBlur=0;}ctx.restore();return true;}
