/* =========================================================
   SAVE / DATA — FireFly 4.0
   ========================================================= */
import {ui} from '../core/dom.js';
export const DEFAULT_DATA={version:5,coins:25,map:'lobby',inventory:{bait:0,reinforcedNet:0,lantern:0,explorationKit:0,luckyCharm:0,masterNet:0},catches:{},discovered:{},quests:{tito_frogs:{status:'available',progress:0}},progression:{xp:0,level:1,resources:{},crafted:{},upgrades:{},stats:{gathered:0,crafted:0,steps:0,events:0}},world:{weather:'sunny',explored:{forest:0,cave:0},landmarks:{},secrets:{},hints:{},discoveries:0},audioEnabled:true};
export function cloneDefaultData(){return JSON.parse(JSON.stringify(DEFAULT_DATA));}
export function loadGame(){try{const raw=localStorage.getItem('firefly-save');if(!raw)return cloneDefaultData();const parsed=JSON.parse(raw);const base=cloneDefaultData();const legacyMap=parsed.map==='village'?'lobby':parsed.map;return {...base,...parsed,map:legacyMap,version:5,inventory:{...base.inventory,...(parsed.inventory||{})},catches:{...base.catches,...(parsed.catches||{})},discovered:{...base.discovered,...(parsed.discovered||{})},quests:{...base.quests,...(parsed.quests||{})},progression:{...base.progression,...(parsed.progression||{}),resources:{...(parsed.progression?.resources||{})},crafted:{...(parsed.progression?.crafted||{})},upgrades:{...(parsed.progression?.upgrades||{})},stats:{...base.progression.stats,...(parsed.progression?.stats||{})}},world:{...base.world,...(parsed.world||{}),explored:{...base.world.explored,...(parsed.world?.explored||{})},landmarks:{...(parsed.world?.landmarks||{})},secrets:{...(parsed.world?.secrets||{})},hints:{...(parsed.world?.hints||{})}}};}catch(error){console.warn('FireFly: save inválido, iniciando novo jogo.',error);return cloneDefaultData();}}
export const save=loadGame();
export function saveGame(){try{localStorage.setItem('firefly-save',JSON.stringify(save));}catch(error){console.warn('FireFly: não foi possível salvar.',error);}if(ui.coins)ui.coins.textContent=save.coins;}
