/* FireFly 7.4 — painéis organizados */
import {ui} from '../core/dom.js';import {save} from '../systems/save.js';import {names,rarity,speciesInfo,itemNames,QUESTS} from '../data/game-data.js';import {quest} from '../systems/quests.js';import {progressSummary} from '../systems/progression.js';import {RESOURCE_TYPES,RECIPES,UPGRADES} from '../data/progression-data.js';import {mapProgress,currentRegion,landmarkStatus,secretStatus} from '../systems/exploration.js';import {economySummary} from '../systems/economy.js';import {orderList} from '../systems/orders.js';import {SHOP_TIERS} from '../data/economy-data.js';
const icon=(letter,cls='')=>`<span class="panel-icon ${cls}" aria-hidden="true">${letter}</span>`;
const header=(title,sub)=>`<button class="close" aria-label="Fechar">×</button><div class="panel-kicker">FIREFLY / REGISTRO</div><h2 class="panel-title">${title}</h2><p class="panel-sub">${sub}</p>`;
export function panel(kind){if(!ui.panel)return;let body='';
if(kind==='map'){const f=mapProgress('forest'),c=mapProgress('cave'),r=currentRegion(),ls=[...landmarkStatus('forest'),...landmarkStatus('cave')],ss=[...secretStatus('forest'),...secretStatus('cave')];ui.panel.innerHTML=header('Mapa de campo',`${r?.name||'Acampamento'} · J para abrir`)+`<div class="stat-grid"><div class="mini-stat">${icon('F')}<b>FLORESTA</b><strong>${f}%</strong><small>explorada</small></div><div class="mini-stat">${icon('C')}<b>CAVERNA</b><strong>${c}%</strong><small>explorada</small></div></div><div class="section-label">DESCOBERTAS</div>${ls.map(l=>`<div class="card"><div>${icon(l.discovered?'◈':'?')}<b>${l.discovered?l.name:'LOCAL DESCONHECIDO'}</b><small>${l.discovered?l.lore:'Explore para registrar no diário.'}</small></div></div>`).join('')}<div class="section-label">MISTÉRIOS</div>${ss.map(s=>`<div class="card"><div>${icon(s.discovered?'✦':'?')}<b>${s.discovered?s.name:'MISTÉRIO NÃO REGISTRADO'}</b><small>${s.discovered?s.hint:'Há algo aqui que ainda não compreendemos.'}</small></div></div>`).join('')}`;
}else if(kind==='bag'){const rs=Object.entries(save.progression?.resources||{}).filter(([,a])=>a>0),it=Object.entries(save.inventory).filter(([,a])=>a>0),cs=Object.entries(save.catches).filter(([id,a])=>a>0);body=[...rs.map(([id,a])=>`<div class="card"><div>${icon('R','resource')}<b>${RESOURCE_TYPES[id]?.name||id}</b><small>${a} · valor ${RESOURCE_TYPES[id]?.value||0} CR</small></div></div>`),...it.map(([id,a])=>`<div class="card"><div>${icon('E','gear')}<b>${itemNames[id]||id}</b><small>${a} unidade(s)</small></div></div>`),...cs.map(([id,a])=>`<div class="card"><div>${icon('F','fauna')}<b>${names[id.split(':')[0]]||id}</b><small>${a} captura(s)${id.includes(':')?' · variante':''}</small></div></div>`)].join('')||'<div class="empty-state">A mochila está vazia.<small>Explore, colete e volte ao acampamento.</small></div>';ui.panel.innerHTML=header('Mochila','Materiais, equipamentos e fauna coletada.')+body;
}else if(kind==='book'){const all=Object.keys(names),disc=all.filter(id=>save.discovered[id]).length;body=all.map(id=>{const d=!!save.discovered[id],i=speciesInfo[id]||{};return `<div class="card"><div>${icon(d?'◇':'?','fauna')}<b>${d?names[id]:'ESPÉCIE DESCONHECIDA'}</b><small>${d?`${rarity[id]} · ${i.habitat||''}`:'Continue explorando para revelar.'}</small>${d?`<small>${i.time||''} · ${i.description||''} · ${i.value||0} CR</small>`:''}</div></div>`}).join('');ui.panel.innerHTML=header('Bestiário','Descobertas registradas: '+disc+'/'+all.length)+body;
}else if(kind==='quest'){const list=Object.values(QUESTS);body=list.map(q=>{const s=quest(q.id),p=Math.min(q.required,s.progress||0),st=s.status==='claimed'?'CONCLUÍDA':s.status==='complete'?'PRONTA':s.status==='active'?`${p}/${q.required}`:'DISPONÍVEL';return `<div class="card"><div>${icon(s.status==='complete'?'✓':'!','quest')}<b>${q.title}</b><small>${q.giver} · ${st} · recompensa ${q.reward.coins} CR</small><div class="bar"><i style="width:${Math.round(p/q.required*100)}%"></i></div></div></div>`}).join('');const orders=orderList().map(o=>`<div class="card"><div>${icon('↗','order')}<b>${o.title}</b><small>${o.state.status==='claimed'?'CONCLUÍDO':o.state.status==='complete'?'PRONTO':o.state.status==='active'?`${o.state.progress}/${o.required}`:'DISPONÍVEL'} · +${o.reward} CR</small></div></div>`).join('');ui.panel.innerHTML=header('Missões & pedidos',`${list.length} missões · contratos da vila`)+body+`<div class="section-label">PEDIDOS DA VILA</div>${orders}`;
}else if(kind==='progress'){const p=progressSummary(),e=economySummary(),tier=SHOP_TIERS[e.tier-1],res=Object.entries(save.progression.resources||{}).map(([id,n])=>`${RESOURCE_TYPES[id]?.name||id} ×${n}`).join(' · ')||'nenhum';ui.panel.innerHTML=header('Progressão',`Nível ${p.level} · ${p.xp} XP · próximo marco ${p.next}`)+`<div class="xp-head"><b>EXPERIÊNCIA</b><strong>LV ${p.level}</strong></div><div class="bar big"><i style="width:${Math.round(p.ratio*100)}%"></i></div><div class="section-label">ECONOMIA</div><div class="card"><div>${icon('CR','coin')}<b>${tier.name}</b><small>${e.rep} reputação · ${e.sold} vendidos · ${e.earned} CR faturados</small></div></div><div class="section-label">MATERIAIS</div><p class="resource-line">${res}</p><div class="section-label">EQUIPAMENTOS</div>${RECIPES.map(r=>`<div class="card"><div>${icon('◆','gear')}<b>${r.name}</b><small>Nível ${r.unlockLevel} · ${r.description}</small></div></div>`).join('')}<div class="section-label">UPGRADES</div>${UPGRADES.map(u=>`<div class="card"><div>${icon('↑','upgrade')}<b>${u.name}</b><small>Nível ${u.level} · ${u.cost} CR · ${u.description}</small></div></div>`).join('')}`;}
ui.panel.classList.remove('hidden');const c=ui.panel.querySelector('.close');if(c)c.onclick=()=>ui.panel.classList.add('hidden');}
