/* =========================================================
   POLISH OVERLAY — arte, profundidade e atmosfera
   ========================================================= */
import {ctx} from '../core/dom.js';import {state,isNight} from '../core/state.js';import {W,H} from '../core/constants.js';import {weatherType} from '../systems/weather.js';
const TAU=Math.PI*2;
function seeded(i){return Math.sin(i*91.731+17.13)*.5+.5;}
function wx(x){return x-state.camera.x;}
export function renderPolishOverlay(){drawAtmosphericDepth();drawAmbientMotes();drawFireflyClusters();drawWaterGlints();drawForegroundFoliage();drawDepthVignette();drawCinematicCorners();}
function drawAtmosphericDepth(){if(state.map==='lobby'||state.map==='village')return;const night=isNight();ctx.save();const g=ctx.createLinearGradient(0,230,0,590);g.addColorStop(0,night?'#12283a12':'#d9f0dd09');g.addColorStop(.5,night?'#0b273015':'#e8e1c00a');g.addColorStop(1,'#020c100d');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);if(state.map==='forest'){for(let i=0;i<7;i++){const x=((i*260+state.camera.x*.035)%1500)-120,y=350+i%3*42;ctx.globalAlpha=.045+(i%2)*.02;ctx.fillStyle=night?'#9eb7ad':'#d7dfc3';ctx.beginPath();ctx.ellipse(x,y,170+(i%3)*50,22+(i%2)*8,0,0,TAU);ctx.fill();}}ctx.restore();}
function drawAmbientMotes(){if(!['forest','cave','village'].includes(state.map))return;const night=isNight(),rain=weatherType()==='rain';if(!night&&!rain)return;ctx.save();const count=state.map==='cave'?22:42;for(let i=0;i<count;i++){const phase=state.t*(.3+seeded(i)*.7)+i*2.7,x=(seeded(i*3+2)*W+Math.sin(phase)*35+i*11)%W,y=315+seeded(i*5+1)*305+Math.cos(phase*.8)*18,pulse=.3+.7*(.5+.5*Math.sin(phase*2.2));ctx.globalAlpha=(night?.3:.1)*pulse;ctx.fillStyle=state.map==='cave'?'#91e2d0':'#f2d77f';ctx.shadowBlur=night?10:5;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.arc(x,y,night?1.7:1.2,0,TAU);ctx.fill();}ctx.restore();}
function drawFireflyClusters(){if(!isNight()||!['forest','village'].includes(state.map))return;ctx.save();for(let i=0;i<26;i++){const base=(i*211+Math.floor(state.camera.x*.12))%5600,x=wx(base),y=365+(i*83)%170+Math.sin(state.t*.9+i)*12;if(x<-30||x>W+30)continue;const pulse=.35+.65*(.5+.5*Math.sin(state.t*2.4+i));ctx.globalAlpha=.16*pulse;ctx.fillStyle='#f5d777';ctx.shadowBlur=14;ctx.shadowColor='#e7c65c';ctx.beginPath();ctx.arc(x,y,2.1,0,TAU);ctx.fill();ctx.globalAlpha=.45*pulse;ctx.beginPath();ctx.arc(x,y,0.75,0,TAU);ctx.fill();}ctx.restore();}
function drawWaterGlints(){if(state.map!=='forest')return;const lakeStart=1450,lakeEnd=2450,p=state.player.x;if(p<lakeStart-800||p>lakeEnd+800)return;ctx.save();for(let i=0;i<22;i++){const world=lakeStart+((i*137+Math.floor(state.t*18))%850),x=wx(world),y=505+(i%7)*9;if(x<-20||x>W+20)continue;ctx.globalAlpha=.18+.12*Math.sin(state.t*1.5+i);ctx.strokeStyle=i%3?'#ccebe1':'#f0d98f';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x-10,y);ctx.lineTo(x+10,y);ctx.stroke();}ctx.restore();}
function drawForegroundFoliage(){if(!['forest','village'].includes(state.map))return;ctx.save();for(let i=0;i<18;i++){const x=(i*79+(state.camera.x*.65)%79)-20,y=610+(i%4)*22;ctx.globalAlpha=.18+(i%3)*.05;ctx.fillStyle=i%2?'#183c34':'#244b3c';ctx.beginPath();ctx.moveTo(x,y+65);ctx.quadraticCurveTo(x-7,y+22,x+2,y);ctx.quadraticCurveTo(x+12,y+25,x+7,y+65);ctx.fill();}ctx.restore();}
function drawDepthVignette(){const g=ctx.createRadialGradient(W*.5,H*.51,170,W*.5,H*.5,770);g.addColorStop(0,'#0000');g.addColorStop(.68,'#06191d08');g.addColorStop(1,isNight()?'#030b12b8':'#071b1d38');ctx.save();ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.restore();}
function drawCinematicCorners(){if(state.fade.value>0)return;ctx.save();ctx.globalAlpha=.2;ctx.strokeStyle='#e7d29d';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(18,58);ctx.lineTo(18,91);ctx.moveTo(18,58);ctx.lineTo(50,58);ctx.moveTo(W-18,58);ctx.lineTo(W-18,91);ctx.moveTo(W-18,58);ctx.lineTo(W-50,58);ctx.stroke();ctx.restore();}
