/* =========================================================
   MAPAS — FireFly World 3.1
   ========================================================= */
import {state} from '../core/state.js';import {save,saveGame} from '../systems/save.js';import {AudioManager} from '../systems/audio.js';import {spawnForest,spawnCave} from '../entities/creatures.js';import {titoDialog} from '../systems/quests.js';import {shopDialog} from '../systems/shop.js';import {startVan} from '../entities/van.js';import {startFishing} from '../systems/fishing.js';import {dialog,closeDialog} from '../render/dialog.js';import {CAVE_ENTRANCE_X,FOREST_POIS} from './spots.js';import {spawnResources,nearestResource,gatherNearest,craft,buyUpgrade,progressSummary} from '../systems/progression.js';import {RECIPES,UPGRADES,RESOURCE_TYPES} from '../data/progression-data.js';import {spawnVillageNPCs} from '../systems/living-world.js';
export function transition(job){if(state.fade.job)return;state.fade.job=job;state.fade.value=.01;}
export function beginMap(id,x=250){transition(()=>{state.map=id;save.map=id;state.player.x=x;state.player.y=515;state.player.vx=0;state.camera.x=Math.max(0,x-350);state.entities=[];state.interactables=[];state.fishing=null;buildMap();saveGame();AudioManager.playMusic(id);AudioManager.playAmbient(id);});}
export function addInteractable(id,x,y,radius,type,onInteract,label){state.interactables.push({id,x,y,radius,type,onInteract,label});}
export function activeInteractable(){const p=state.player;return state.interactables.filter(o=>Math.abs(o.x-p.x)<o.radius&&Math.abs(o.y-p.y)<95).sort((a,b)=>Math.abs(a.x-p.x)-Math.abs(b.x-p.x))[0];}
function caveDialog(){dialog('Fenda Cintilante','Uma corrente fria atravessa as árvores. Há marcas antigas na pedra e um brilho azul vindo de baixo.',[['ENTRAR',()=>{closeDialog();beginMap('cave',180)}],['AGORA NÃO',closeDialog]]);}
function workshopDialog(){const s=progressSummary();const buttons=[['FECHAR',closeDialog]];for(const r of RECIPES){const cost=Object.entries(r.cost).map(([id,n])=>`${RESOURCE_TYPES[id].icon}${n}`).join(' ');buttons.unshift([`${r.name} · ${cost}`,()=>{craft(r.id);closeDialog()}]);}dialog('Bancada de Tito',`Nível ${s.level} · XP ${s.xp}. Transforme recursos em equipamentos permanentes.`,buttons);}
function upgradeDialog(){const buttons=[['FECHAR',closeDialog]];for(const u of UPGRADES)buttons.unshift([`${u.name} · ${u.cost}✦`,()=>{buyUpgrade(u.id);closeDialog()});dialog('Oficina da Vila','Use moedas para melhorar sua expedição. Upgrades são permanentes.',buttons);}
function npcDialog(id){const lines={luna:['Luna','As flores mudam depois do pôr do sol. Se você prestar atenção, vai descobrir por quê.'],theo:['Theo','A pedreira tem minério suficiente para melhorar quase qualquer ferramenta.'],maya:['Maya','Toda manhã chega alguma coisa nova para a vila. Volte mais tarde.'],nico:['Nico','A lagoa fica diferente quando a lua sobe. Os peixes também.']};const d=lines[id];if(d)dialog(d[0],d[1],[['FECHAR',closeDialog]]);}
export function buildMap(){state.interactables=[];if(state.map==='village'){spawnVillageNPCs();addInteractable('tito',460,505,70,'npc',titoDialog,'Falar com Tito');addInteractable('shop',630,505,110,'shop',shopDialog,'Entrar na lojinha');addInteractable('workshop',790,505,100,'craft',workshopDialog,'Usar bancada');addInteractable('upgrade',875,505,100,'upgrade',upgradeDialog,'Melhorar equipamentos');addInteractable('van',980,510,150,'vehicle',startVan,'Explorar de van');for(const id of ['luna','theo','maya','nico']){const n=state.npcs.find(v=>v.id===id);addInteractable('npc-'+id,n.x,505,62,'npc',()=>npcDialog(id),`Falar com ${id}`);}}
if(state.map==='forest'){spawnForest();spawnResources();addInteractable('village',80,510,110,'door',()=>beginMap('village',1090),'Voltar para Vila Lumina');addInteractable('fish',1840,525,330,'fishing',startFishing,'Pescar na Lagoa Cintilante');addInteractable('cave',CAVE_ENTRANCE_X,505,155,'door',caveDialog,'Explorar a Caverna Ecoante');for(const poi of FOREST_POIS){if(poi.type==='cabin')addInteractable(poi.id,poi.x,500,80,'poi',()=>dialog(poi.label,'Uma construção antiga tomada pela floresta. Talvez alguém tenha vivido aqui.',[['FECHAR',closeDialog]]),poi.label);if(poi.type==='burrow')addInteractable(poi.id,poi.x,535,70,'poi',()=>dialog(poi.label,'Há marcas pequenas no chão. Alguma criatura usa esta toca.',[['FECHAR',closeDialog]]),poi.label);}}
if(state.map==='cave'){spawnCave();spawnResources();addInteractable('exit',90,510,120,'door',()=>beginMap('forest',CAVE_ENTRANCE_X-220),'Voltar à floresta');}}
export function handleWorldInteraction(){if(nearestResource())return gatherNearest();const interactable=activeInteractable();if(interactable){interactable.onInteract();return true;}return false;}
