/* =========================================================
   MAPAS — FireFly World 3.3
   ========================================================= */
import {state} from '../core/state.js';import {save,saveGame} from '../systems/save.js';import {AudioManager} from '../systems/audio.js';import {spawnForest,spawnCave} from '../entities/creatures.js';import {titoDialog} from '../systems/quests.js';import {shopDialog} from '../systems/shop.js';import {startVan} from '../entities/van.js';import {startFishing} from '../systems/fishing.js';import {dialog,closeDialog} from '../render/dialog.js';import {CAVE_ENTRANCE_X,FOREST_POIS} from './spots.js';import {spawnResources,nearestResource,gatherNearest,craft,buyUpgrade,progressSummary} from '../systems/progression.js';import {RECIPES,UPGRADES,RESOURCE_TYPES} from '../data/progression-data.js';import {spawnVillageNPCs} from '../systems/living-world.js';
export function transition(job){if(state.fade.job)return;state.fade.job=job;state.fade.value=.01;}
export function beginMap(id,x=250){transition(()=>{state.map=id;save.map=id;state.player.x=x;state.player.y=515;state.player.vx=0;state.camera.x=Math.max(0,x-350);state.entities=[];state.interactables=[];state.npcs=[];state.fishing=null;buildMap();saveGame();AudioManager.playMusic(id);AudioManager.playAmbient(id);});}
export function addInteractable(id,x,y,radius,type,onInteract,label){state.interactables.push({id,x,y,radius,type,onInteract,label});}
export function activeInteractable(){const p=state.player;return state.interactables.filter(o=>Math.abs(o.x-p.x)<o.radius&&Math.abs(o.y-p.y)<95).sort((a,b)=>Math.abs(a.x-p.x)-Math.abs(b.x-p.x))[0];}
export function clickedInteractable(screenX,screenY){const worldX=state.camera.x+screenX,worldY=screenY;const hit=state.interactables.filter(o=>Math.abs(o.x-worldX)<Math.max(55,o.radius*.8)&&Math.abs(o.y-worldY)<90).sort((a,b)=>Math.abs(a.x-worldX)-Math.abs(b.x-worldX))[0];if(hit){hit.onInteract();return true;}return false;}
function caveDialog(){dialog('Fenda Cintilante','Uma corrente fria atravessa as árvores. Há marcas antigas na pedra e um brilho azul vindo de baixo.',[['ENTRAR',()=>{closeDialog();beginMap('cave',180)}],['AGORA NÃO',closeDialog]]);}
function workshopDialog(){const s=progressSummary();const buttons=[['FECHAR',closeDialog]];for(const r of RECIPES){const cost=Object.entries(r.cost).map(([id,n])=>`${RESOURCE_TYPES[id].icon}${n}`).join(' ');buttons.unshift([`${r.name} · ${cost}`,()=>{craft(r.id);closeDialog()}]);}dialog('Bancada da Vila','Nível '+s.level+' · XP '+s.xp+'. Transforme recursos em equipamentos permanentes.',buttons);}
function upgradeDialog(){const buttons=[['FECHAR',closeDialog]];for(const u of UPGRADES)buttons.unshift([`${u.name} · ${u.cost}✦`,()=>{buyUpgrade(u.id);closeDialog()}]);dialog('Oficina da Vila','Use moedas para melhorar sua expedição. Upgrades são permanentes.',buttons);}
function npcDialog(id){const lines={luna:['Luna','As flores mudam depois do pôr do sol. Se você prestar atenção, vai descobrir por quê.'],theo:['Theo','A forja não para. Traga minério e eu transformo isso em equipamento.'],maya:['Maya','Toda manhã chega alguma coisa nova. Confira meu estoque depois do amanhecer.'],nico:['Nico','A lagoa fica diferente quando a lua sobe. Os peixes também.']};const d=lines[id];if(d)dialog(d[0],d[1],[['FECHAR',closeDialog]]);}
export function buildMap(){state.interactables=[];if(state.map==='lobby'){addInteractable('village-gate',1150,510,145,'door',()=>beginMap('village',120),'Entrar na Vila Lumina');addInteractable('shop',560,505,95,'shop',shopDialog,'Abrir lojinha');addInteractable('van',790,510,150,'vehicle',startVan,'Explorar de van');}
if(state.map==='village'){spawnVillageNPCs();const byId=id=>state.npcs.find(v=>v.id===id);addInteractable('tito',byId('tito').x,505,65,'npc',titoDialog,'Falar com Tito');addInteractable('shop',520,505,90,'shop',shopDialog,'Entrar na lojinha');addInteractable('workshop',760,505,95,'craft',workshopDialog,'Usar bancada');addInteractable('upgrade',910,505,95,'upgrade',upgradeDialog,'Melhorar equipamentos');addInteractable('back-lobby',80,510,135,'door',()=>beginMap('lobby',1110),'Voltar ao acampamento');for(const id of ['luna','theo','maya','nico']){const n=byId(id);addInteractable('npc-'+id,n.x,505,62,'npc',()=>npcDialog(id),'Falar com '+id);}}
if(state.map==='forest'){spawnForest();spawnResources();addInteractable('village',80,510,150,'door',()=>beginMap('village',1780),'Ir para Vila Lumina');addInteractable('fish',1840,525,330,'fishing',startFishing,'Pescar na Lagoa Cintilante');addInteractable('cave',CAVE_ENTRANCE_X,505,155,'door',caveDialog,'Explorar a Caverna Ecoante');for(const poi of FOREST_POIS){if(poi.type==='cabin')addInteractable(poi.id,poi.x,500,80,'poi',()=>dialog(poi.label,'Uma construção antiga tomada pela floresta. Talvez alguém tenha vivido aqui.',[['FECHAR',closeDialog]]),poi.label);if(poi.type==='burrow')addInteractable(poi.id,poi.x,535,70,'poi',()=>dialog(poi.label,'Há marcas pequenas no chão. Alguma criatura usa esta toca.',[['FECHAR',closeDialog]]),poi.label);}}
if(state.map==='cave'){spawnCave();spawnResources();addInteractable('exit',90,510,120,'door',()=>beginMap('forest',CAVE_ENTRANCE_X-220),'Voltar à floresta');}}
export function handleWorldInteraction(){if(nearestResource())return gatherNearest();const interactable=activeInteractable();if(interactable){interactable.onInteract();return true;}return false;}
