/* =========================================================
   MAPAS — FireFly World 4.0
   ========================================================= */
import {state} from '../core/state.js';import {save,saveGame} from '../systems/save.js';import {AudioManager} from '../systems/audio.js';import {spawnForest,spawnCave} from '../entities/creatures.js';import {titoDialog} from '../systems/quests.js';import {shopDialog} from '../systems/shop.js';import {startVan} from '../entities/van.js';import {startFishing} from '../systems/fishing.js';import {dialog,closeDialog} from '../render/dialog.js';import {CAVE_ENTRANCE_X,FOREST_POIS} from './spots.js';import {spawnResources,nearestResource,gatherNearest,craft,buyUpgrade,progressSummary} from '../systems/progression.js';import {RECIPES,UPGRADES,RESOURCE_TYPES} from '../data/progression-data.js';import {spawnVillageNPCs} from '../systems/living-world.js';import {LANDMARKS,SECRETS} from '../data/world-4-data.js';import {discoverLandmark,discoverSecret} from '../systems/exploration.js';
export function transition(job){if(state.fade.job)return;state.fade.job=job;state.fade.value=.01;}
export function beginMap(id,x=250){transition(()=>{state.map=id;save.map=id;state.player.x=x;state.player.y=515;state.player.vx=0;state.camera.x=Math.max(0,x-350);state.entities=[];state.resources=[];state.interactables=[];state.npcs=[];state.particles=[];state.fishing=null;state.worldEvent=null;buildMap();saveGame();AudioManager.playMusic(id);AudioManager.playAmbient(id);});}
export function addInteractable(id,x,y,radius,type,onInteract,label){state.interactables.push({id,map:state.map,x,y,radius,type,onInteract,label});}
export function activeInteractable(){const p=state.player;return state.interactables.filter(o=>o.map===state.map&&Math.abs(o.x-p.x)<o.radius&&Math.abs(o.y-p.y)<95).sort((a,b)=>Math.abs(a.x-p.x)-Math.abs(b.x-p.x))[0];}
export function clickedInteractable(screenX,screenY){const worldX=state.camera.x+screenX,worldY=screenY;const hit=state.interactables.filter(o=>o.map===state.map&&Math.abs(o.x-worldX)<Math.max(55,o.radius*.8)&&Math.abs(o.y-worldY)<90).sort((a,b)=>Math.abs(a.x-worldX)-Math.abs(b.x-worldY))[0];if(hit){hit.onInteract();return true;}return false;}
function landmarkDialog(l){const discovered=!!save.world.landmarks[l.id];if(!discovered)discoverLandmark(l.id);dialog(l.name,l.lore,[['FECHAR',closeDialog]]);}
function secretDialog(s){if(!save.world.secrets[s.id]){const req=s.requires==='lantern'&&!save.inventory.lantern?'lanterna':s.requires==='night'?'noite':null;if(req){dialog('Algo não fecha',s.hint,[['FECHAR',closeDialog]]);return;}discoverSecret(s.id);}dialog(s.name,s.hint+' Você encontrou uma passagem que poucos perceberiam.',[['FECHAR',closeDialog]]);}
function caveDialog(){dialog('Fenda Cintilante','Uma corrente fria atravessa as árvores. Há marcas antigas na pedra e um brilho azul vindo de baixo.',[['ENTRAR',()=>{closeDialog();beginMap('cave',180)}],['AGORA NÃO',closeDialog]]);}
function workshopDialog(){const s=progressSummary();const buttons=[['FECHAR',closeDialog]];for(const r of RECIPES){const cost=Object.entries(r.cost).map(([id,n])=>`${RESOURCE_TYPES[id].icon}${n}`).join(' ');buttons.unshift([`${r.name} · ${cost}`,()=>{craft(r.id);closeDialog()}]);}dialog('Bancada da Vila','Nível '+s.level+' · XP '+s.xp+'. Transforme recursos em equipamentos permanentes.',buttons);}
function upgradeDialog(){const buttons=[['FECHAR',closeDialog]];for(const u of UPGRADES)buttons.unshift([`${u.name} · ${u.cost}✦`,()=>{buyUpgrade(u.id);closeDialog()}]);dialog('Oficina da Vila','Use moedas para melhorar sua expedição. Upgrades são permanentes.',buttons);}
function npcDialog(id){const lines={luna:['Luna','As flores mudam depois do pôr do sol. Se você prestar atenção, vai descobrir por quê.'],theo:['Theo','A forja não para. Traga minério e eu transformo isso em equipamento.'],maya:['Maya','Toda manhã chega alguma coisa nova. Confira meu estoque depois do amanhecer.'],nico:['Nico','A lagoa fica diferente quando a lua sobe. Os peixes também.']};const d=lines[id];if(d)dialog(d[0],d[1],[['FECHAR',closeDialog]]);}
export function buildMap(){state.interactables=[];state.resources=[];state.npcs=[];
 if(state.map==='lobby'){addInteractable('village-gate',1150,510,120,'door',()=>beginMap('village',150),'Entrar na Vila Lumina');addInteractable('shop',560,505,90,'shop',shopDialog,'Abrir lojinha');addInteractable('van',790,510,130,'vehicle',startVan,'Planejar expedição na van');return;}
 if(state.map==='village'){spawnVillageNPCs();const byId=id=>state.npcs.find(v=>v.id===id);const tito=byId('tito');addInteractable('tito',tito.x,505,58,'npc',titoDialog,'Falar com Tito');addInteractable('shop',520,505,82,'shop',shopDialog,'Entrar na lojinha');addInteractable('workshop',780,505,88,'craft',workshopDialog,'Usar bancada');addInteractable('upgrade',940,505,88,'upgrade',upgradeDialog,'Melhorar equipamentos');addInteractable('back-lobby',60,510,100,'door',()=>beginMap('lobby',1110),'Voltar ao acampamento');for(const id of ['luna','theo','maya','nico']){const n=byId(id);if(n)addInteractable('npc-'+id,n.x,505,54,'npc',()=>npcDialog(id),'Falar com '+n.id[0].toUpperCase()+n.id.slice(1));}return;}
 if(state.map==='forest'){spawnForest();spawnResources();addInteractable('back-lobby',70,515,115,'door',()=>beginMap('lobby',1110),'Voltar ao acampamento');addInteractable('fish',1840,525,330,'fishing',startFishing,'Pescar na Lagoa Cintilante');addInteractable('cave',CAVE_ENTRANCE_X,505,155,'door',caveDialog,'Explorar a Caverna Ecoante');for(const poi of FOREST_POIS){if(poi.type==='cabin')addInteractable(poi.id,poi.x,500,80,'poi',()=>dialog(poi.label,'Uma construção antiga tomada pela floresta. Talvez alguém tenha vivido aqui.',[['FECHAR',closeDialog]]),poi.label);if(poi.type==='burrow')addInteractable(poi.id,poi.x,535,70,'poi',()=>dialog(poi.label,'Há marcas pequenas no chão. Alguma criatura usa esta toca.',[['FECHAR',closeDialog]]),poi.label);}for(const l of LANDMARKS.filter(v=>v.map==='forest'))addInteractable('landmark-'+l.id,l.x,500,78,'landmark',()=>landmarkDialog(l),l.name);for(const s of SECRETS.filter(v=>v.map==='forest'))addInteractable('secret-'+s.id,s.x,510,62,'secret',()=>secretDialog(s),s.name);return;}
 if(state.map==='cave'){spawnCave();spawnResources();addInteractable('exit',90,510,120,'door',()=>beginMap('forest',CAVE_ENTRANCE_X-220),'Voltar à floresta');for(const l of LANDMARKS.filter(v=>v.map==='cave'))addInteractable('landmark-'+l.id,l.x,500,78,'landmark',()=>landmarkDialog(l),l.name);for(const s of SECRETS.filter(v=>v.map==='cave'))addInteractable('secret-'+s.id,s.x,510,62,'secret',()=>secretDialog(s),s.name);return;}}
export function handleWorldInteraction(){if(nearestResource())return gatherNearest();const interactable=activeInteractable();if(interactable){interactable.onInteract();return true;}return false;}
